### ISSUE TITLE
Map display too large

### ISSUE THREAD

**Issue by bussio** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#1]
Yesterday, the display of the map of the Roborock S6's course worked wonderfully. This morning there was a new version of the integration ... the map is still displayed, but only a small part of it. See pictures as follows.
This is the map on my iPhone:
![IMG_6046](https://user-images.githubusercontent.com/48105172/94806865-f906bc00-03ee-11eb-89e6-08d0e9c9d075.PNG)

and this is the map in HA:
![2020-10-01_13-56-54](https://user-images.githubusercontent.com/48105172/94806926-1d629880-03ef-11eb-891f-61a6330531bc.png)

**Comment by PiotrMachowski** [comment]
Do you have `trim` section in your config?

**Comment by bussio** [comment]
Yes, I have the trim values you gave in your example:
trim:
        top: 10
        bottom: 20
        left: 30
        right: 40

**Comment by PiotrMachowski** [comment]
This example shows what you _can_ configure, not necessarily what you _should_ configure. Trimming section enables map trimming, so in your case map was trimmed:
 * 10% from the top
 * 20% from the bottom
 * 30% from the left side
 * 40% from the right side

When you remove this section from your config map will be restored to full size.

**Comment by bussio** [comment]
Okay, yeah, that works. Let's play around with these values a bit.
