### ISSUE TITLE
Missing library?

### ISSUE THREAD

**Issue by tmjo** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#101]
First of all, looks like great work! 

I just started using the integration, but I had to manually install the Crypto library with pip. Shouldn't it be included in the manifest to ensure automatic installation? I assume it is **pycryptodome**, at least it worked when I installed this with pip.

**Comment by PiotrMachowski** [comment]
It used to be there, but I have removed it, because I thought that I have removed its usages... Well, apparently not. Thanks for the finding!

**Comment by PiotrMachowski** [comment]
I have removed this dependency in v1.1.0
