### ISSUE TITLE
Setting color of zones only applies on zone 1

### ISSUE THREAD

**Issue by Koendejongh** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#106]
When adjusting the color for each zone, it only works on the fist zone.

**Comment by PiotrMachowski** [comment]
Can you please attach your config and a map screenshot?

**Comment by Koendejongh** [comment]
Many thanks for you quick reply and for the map extraction program itself.

Here is my config excluding login:
      map_transformation:
        scale: 2.5
        rotate: 90
      colors:
        color_map_outside: [43, 46, 48]
        color_zones: [43, 46, 48]
      room_colors:
          1: [43, 46, 48] 
          2: [43, 46, 48]
          3: [43, 46, 48]
          4: [43, 46, 48]
          5: [43, 46, 48]
          6: [43, 46, 48]
          7: [43, 46, 48]
          8: [43, 46, 48]
          9: [43, 46, 48]
          10: [43, 46, 48]
          11: [43, 46, 48]
          12: [43, 46, 48]
          13: [43, 46, 48]
          14: [43, 46, 48]
          15: [43, 46, 48]
          16: [43, 46, 48]
      draw:
      - charger
      - path
      - goto_path
      - predicted_path
      - vacuum_position

![screenshot map](https://user-images.githubusercontent.com/73291364/116209676-6fc82580-a742-11eb-99b6-4d22dd36365c.jpg)

Kind regards,
Koen

**Comment by Koendejongh** [comment]
![screenshot config](https://user-images.githubusercontent.com/73291364/116210027-c7ff2780-a742-11eb-8278-3a9a8654c2b0.jpg)

**Comment by PiotrMachowski** [comment]
You can add `room_numbers` in [attributes configuration](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#attributes-configuration) to find out all room numbers that you can use (they can be greater than 16).

```
      map_transformation:
        scale: 2.5
        rotate: 90
      colors:
        color_map_outside: [43, 46, 48]
        color_zones: [43, 46, 48]
      room_colors:
          1: [43, 46, 48] 
          2: [43, 46, 48]
          3: [43, 46, 48]
          4: [43, 46, 48]
          5: [43, 46, 48]
          6: [43, 46, 48]
          7: [43, 46, 48]
          8: [43, 46, 48]
          9: [43, 46, 48]
          10: [43, 46, 48]
          11: [43, 46, 48]
          12: [43, 46, 48]
          13: [43, 46, 48]
          14: [43, 46, 48]
          15: [43, 46, 48]
          16: [43, 46, 48]
      draw:
      - charger
      - path
      - goto_path
      - predicted_path
      - vacuum_position
      attributes:
      - room_numbers
```

**Comment by Koendejongh** [comment]
Correct, many thanks 😊

**Comment by PiotrMachowski** [comment]
So, you have found rooms with numbers greater than 16 and everything works now?

**Comment by Koendejongh** [comment]
Yes, and I want you to buy a coffee but somehow paypal refuses.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by PiotrMachowski** [comment]
I have some problems with PayPal, I hope it will be available soon

**Comment by PiotrMachowski** [comment]
There were some problems but it should be fixed now... 😵
