### ISSUE TITLE
Country

### ISSUE THREAD

**Issue by polysa** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#11]
Hello. In Mi Home I use Cyprus as my country and in FloleVac I need to choose Europe in order to connect.

From the documantation only the following counries are available: One of: ru, us, tw, sg, cn, de.

I tried EU and CY but HA is not valitating the YAML. 

Any help?

**Comment by PiotrMachowski** [comment]
You should probably use `de` server, as it seems to be the one used for Europe.

**Comment by polysa** [comment]
> You should probably use `de` server, as it seems to be the one used for Europe.

Hm ok. Still no yaml validation with de. My vacuum is roborock s6 maxv. Maybe is not supported.

**Comment by gotschi** [comment]
s6 maxv is supported

**Comment by PiotrMachowski** [comment]
@polysa can you show your config?

**Comment by polysa** [comment]
> @polysa can you show your config?

Yes sure:

`camera:
    - platform: xiaomi_cloud_map_extractor
      host: 192.168.1.***
      token: !secret vacuum_token
      username: !secret xiaomi_email
      password: !secret xiaomi_pass
      country: "de"   
      name: "s6maxV Map Camera"`

**Comment by polysa** [comment]
I have install from hacs and everything is working now. 

Thank you Closing this threat.
