### ISSUE TITLE
Documentation for example draw: ['all'] is incorrect >> change to ["all"]

### ISSUE THREAD

**Issue by danielntamasi** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#120]
Documentation for the example is incorrect. As mentioned above, all should be in double quotation marks to work.

Suggestion for change:
from:
    draw: ['all'] 
to:
    draw: ["all"]

**Comment by PiotrMachowski** [comment]
Are you sure? As far as I know single and double quotes are mostly interchangeable in yaml

**Comment by danielntamasi** [comment]
it didn't work for me with single ones and worked perfectly with double :)

**Comment by PiotrMachowski** [comment]
I will check it out

**Comment by PiotrMachowski** [comment]
Both versions work for me
