### ISSUE TITLE
Integration not found

### ISSUE THREAD

**Issue by Jese44** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#125]
My HA was running normally, but suddenly HA gave errors when my automation tried to star everyday cleaning. I haven't done any modification to my HA for a while so i have no clue what could cause this. My roborock system worked great for~3-6 months... Though i can't tell if there has been some autoupdates for something...

"Logger: homeassistant.config
Source: config.py:849
First occurred: June 3, 2021, 9:02:19 PM (1 occurrences)
Last logged: June 3, 2021, 9:02:19 PM

Platform error: camera - Integration 'xiaomi_cloud_map_extractor' not found."

**Comment by PiotrMachowski** [comment]
Which version of integration do you have?
Which version of HA do you have?

**Comment by Jese44** [comment]
Unfortunatelly i have no access to HA physically but i noticed that my roborock is not connected to my wifi, that may be one issue, but i cant tell 100%..

**Comment by Jese44** [comment]
Home Assistant 2021.6.0
Home Assistant OS

I set integration up as manual back when i set it up, how can i check its version?

**Comment by PiotrMachowski** [comment]
You can check integration's version in `/custom_components/xiaomi_cloud_map_extractor/manifest.json`

**Comment by Jese44** [comment]
V1.1.1

**Comment by PiotrMachowski** [comment]
The problem might be caused by the vacuum being disconnected from wifi during HA start, try connecting it to wifi and restart HA

**Comment by Jese44** [comment]
Ok, i'll try that asap, thanks for now!

**Comment by PiotrMachowski** [comment]
Is it working now?

**Comment by Jese44** [comment]
I came sick and hava been unable to get back home... Hopefully i can check it on upcoming weekend.

**Comment by Jese44** [comment]
Hey, so problem was roborock error (~user error, kind of) Robo has gone into a "no-go zone" defined in map and it had no clue how to get out of it, so it had shut itself down and thats why my HA didn't work.
