### ISSUE TITLE
Support for multiple vacuum?

### ISSUE THREAD

**Issue by noiseboy303** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#134]
Hello,

  I was wondering if it supports multiple vacuums, we have 2 and I can only see one map!

Thanks for the great work!

**Comment by PiotrMachowski** [comment]
Yes, you have to define 2 cameras with different `name` provided.

Duplicate of #119

**Comment by noiseboy303** [comment]
Oh Geez, Sorry, I did not see the post 119!

Thanks for the quick answer!


Martin Pare
***@***.***
