### ISSUE TITLE
Scale factor not applied to the Robo and Dock station circles

### ISSUE THREAD

**Issue by leva3000** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#14]
I set the scale factor to 3 and it looks like the Robo and Dock station circles remain small

**Comment by PiotrMachowski** [comment]
It was done intentionally, I will add a config for that

**Comment by PiotrMachowski** [comment]
Done 
![image](https://user-images.githubusercontent.com/6118709/95935758-5417b600-0dd4-11eb-9cb6-3363ce6215f9.png)
