### ISSUE TITLE
Add an attribute with the rooms where the cleaning is currently taking place

### ISSUE THREAD

**Issue by leva3000** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#15]
If it's possible, please add an attribute with the rooms where the cleaning is currently taking place. Thanks!

**Comment by PiotrMachowski** [comment]
I was thinking about it yesterday :) it should be possible

**Comment by PiotrMachowski** [comment]
Aaaaand done

**Comment by leva3000** [comment]
Thanks for your fast response! Now I'll be able to set up switches for room cleaning with proper status and create proper notifications

**Comment by pznamenskii** [comment]
> Thanks for your fast response! Now I'll be able to set up switches for room cleaning with proper status and create proper notifications

please share your ideas when you code them in, interested to see the result.

**Comment by laccio85** [comment]
> > Thanks for your fast response! Now I'll be able to set up switches for room cleaning with proper status and create proper notifications
> 
> please share your ideas when you code them in, interested to see the result.

very interesting idea, please share with us
