### ISSUE TITLE
Xiaomi Vacuum Cleaner dont't work after restart

### ISSUE THREAD

**Issue by Judocrafter** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#155]
When I restart the home assistant, the Xiaomi Vacum Cleaner no longer works. I then have to delete the device "xiaomi Vacuum Cleaner" under Devices and restart the Home Assistant. Then it works again until the home assistant is started again.
![image](https://user-images.githubusercontent.com/42749857/125629394-2944457a-cb34-4007-bee6-38d48fb465cf.png)

This is my configuration:
![image](https://user-images.githubusercontent.com/42749857/125629994-b67f60c8-b24d-49de-86dc-e2514e932d54.png)

What could be the problem?
Homeassistant runs on a raspberry pi.

**Comment by PiotrMachowski** [comment]
Does the camera still work?
You probably don't need all these values in `attributes` section, `calibration_points` should be enough

**Comment by Judocrafter** [comment]
Many thanks for the help.
I solved the problem.
It wasn't because of the attributes. I deactivated the vacuum cleaner in the configuration.yaml. :

```
#vacuum:
#  - platform: xiaomi_miio
#    host: 192.168.x.xx
#    token: xxxxxxxxxxxxxxxxxxx
```

Then I installed the Xiaomi Miio integration via the interface and now it works.
![image](https://user-images.githubusercontent.com/42749857/125958835-d943c09b-f1e4-4790-a654-283f296ec39c.png)

**Comment by PiotrMachowski** [comment]
I know it wasn't because of attributes, but they unnecessarily add to CPU, RAM and database usage
