### ISSUE TITLE
Roborock S7 not working

### ISSUE THREAD

**Issue by jscherry** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#176]
I've been using the map card with camera for some time with an S6. I just started using an S7. I have the vacuum integrated in home assistant and everything works but I can't get the map card working? I have the correct user, password, ip, and token in the config but home assistant throws an error about the token?
Logger: homeassistant.config
Source: config.py:464
First occurred: 10:22:00 PM (1 occurrences)
Last logged: 10:22:00 PM

Invalid config for [camera.xiaomi_cloud_map_extractor]: expected str for dictionary value @ data['token']. Got 39437041786430774232726858317662. (See /config/configuration.yaml, line 228). Please check the docs at https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor

I know the token is correct because I used the old method of backing up my iphone, using ibackup and terminal. I also used your token extractor on windows and got the same exact token from both methods?
What am I missing?
Thanks

**Comment by PiotrMachowski** [comment]
Just wrap your token with double quotes and it should be fine :)

**Comment by PiotrMachowski** [comment]
Does it work for you?

**Comment by jscherry** [comment]
Yes finally got it working
