### ISSUE TITLE
Unable to retrieve map data

### ISSUE THREAD

**Issue by PiotrasHASS** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#180]
Logger: custom_components.xiaomi_cloud_map_extractor.camera
Source: custom_components/xiaomi_cloud_map_extractor/camera.py:333
Integration: xiaomi_cloud_map_extractor (documentation, issues)
First occurred: 15:20:02 (1 occurrences)
Last logged: 15:20:02

Unable to retrieve map data

**Comment by PiotrMachowski** [comment]
Model?

**Comment by PiotrasHASS** [comment]
Xiaomi s5 I s6

pon., 1 lis 2021, 16:18 użytkownik Piotr Machowski ***@***.***>
napisał:

**Comment by PiotrMachowski** [comment]
Was it a single occurrence? Does the map work despite error? Please paste your config

**Comment by fi-sch** [comment]
I also experience some problem with authentication. Not sure when it started, but it was working last friday for sure. I get following error in the HA log:

`Logger: custom_components.xiaomi_cloud_map_extractor.common.xiaomi_cloud_connector
Source: custom_components/xiaomi_cloud_map_extractor/common/xiaomi_cloud_connector.py:86 
Integration: xiaomi_cloud_map_extractor (documentation, issues) 
First occurred: 17:35:42 (1 occurrences) 
Last logged: 17:35:42

Additional authentication required. Open following URL using device that has the same public IP, as your Home Assistant instance: https://account.xiaomi.com/xxxxxxx`

When I try to open the page I get:
<img width="913" alt="image" src="https://user-images.githubusercontent.com/59969726/139908683-4081aea9-e5a5-4e41-9bc9-6218d5cc6c94.png">
No content loading, unfortunately. I disabled AdGuard and other ad/content/privacy-blockers.

**Comment by pixeldublu** [comment]
> I also experience some problem with authentication. Not sure when it started, but it was working last friday for sure. I get following error in the HA log:
> 
> ```
> Logger: custom_components.xiaomi_cloud_map_extractor.common.xiaomi_cloud_connector
> Source: custom_components/xiaomi_cloud_map_extractor/common/xiaomi_cloud_connector.py:86 
> Integration: xiaomi_cloud_map_extractor (documentation, issues) 
> First occurred: 17:35:42 (1 occurrences) 
> Last logged: 17:35:42
> 
> Additional authentication required. Open following URL using device that has the same public IP, as your Home Assistant instance: https://account.xiaomi.com/xxxxxxx
> ```
> 
> When I try to open the page I get: <img alt="image" width="913" src="https://user-images.githubusercontent.com/59969726/139908683-4081aea9-e5a5-4e41-9bc9-6218d5cc6c94.png"> No content loading, unfortunately. I disabled AdGuard and other ad/content/privacy-blockers.

Got the exact same issue...

**Comment by ZebastianBjorkqvist** [comment]
Im also having the same issue.
Disabled AdGuard and other ad blocking services, tried different browsers and devices.

**Comment by PiotrMachowski** [comment]
I have an idea for a potential fix, but it will take some time for me to implement it

**Comment by luka6000** [comment]
same here. Two factor url is not working

**Comment by agustusbotti** [comment]
Same problem. After update to 2021.10.7 and OS 6.6

**Comment by LeandroIssa** [comment]
> I also experience some problem with authentication. Not sure when it started, but it was working last friday for sure. I get following error in the HA log:
> 
> ```
> Logger: custom_components.xiaomi_cloud_map_extractor.common.xiaomi_cloud_connector
> Source: custom_components/xiaomi_cloud_map_extractor/common/xiaomi_cloud_connector.py:86 
> Integration: xiaomi_cloud_map_extractor (documentation, issues) 
> First occurred: 17:35:42 (1 occurrences) 
> Last logged: 17:35:42
> 
> Additional authentication required. Open following URL using device that has the same public IP, as your Home Assistant instance: https://account.xiaomi.com/xxxxxxx
> ```
> 
> When I try to open the page I get: <img alt="image" width="913" src="https://user-images.githubusercontent.com/59969726/139908683-4081aea9-e5a5-4e41-9bc9-6218d5cc6c94.png"> No content loading, unfortunately. I disabled AdGuard and other ad/content/privacy-blockers.


I have the same problem, the log link doesn't work and Xiaomi's page is blank.

![Captura de tela 2021-11-03 021722](https://user-images.githubusercontent.com/67451572/140013011-0f9f949d-6e49-4398-92cf-f6c42ed355a5.jpg)
![Captura de tela 2021-11-03 021704](https://user-images.githubusercontent.com/67451572/140013232-00c53805-3fda-4a4e-b61d-b0397fac84d8.jpg)
![Captura de tela 2021-11-03 021632](https://user-images.githubusercontent.com/67451572/140013241-d26cc90b-89c4-4121-b7ef-b7485389e66d.jpg)

**Comment by mcfly2283-ai** [comment]
The Link is only working for short time. After try to catch the Link instantly after a reboot, it was possible to MFA to my phone. Also deactivated my AdGuard-Protection for that time, i dont know if it cares.

**Comment by fi-sch** [comment]
> The Link is only working for short time. After try to catch the Link instantly after a reboot, it was possible to MFA to my phone. Also deactivated my AdGuard-Protection for that time, i dont know if it cares.

Thanks, I will try that later today. Maybe I was not quick enough.

**Comment by sabouarthur** [comment]
After a hard reset it comes back without any action from my side
![image](https://user-images.githubusercontent.com/65715321/140028395-10f67deb-552a-4512-a331-d8ca3ff590a7.png)

**Comment by gogenzuller** [comment]
I have the same problem. Disabled adguard. Restarted HA. Refreshed the page with the log until a message appeared about the need to re-authorize. I immediately opened the link, got to the account confirmation page. Confirmed via sms. On the page I received the answer "OK". But in HA the error still remained, the map is not displayed and after restarting HA again requires to follow the link for autorize.

**Comment by sagitt** [comment]
same here.

**Comment by mcfly2283** [comment]
> I have the same problem. Disabled adguard. Restarted HA. Refreshed the page with the log until a message appeared about the need to re-authorize. I immediately opened the link, got to the account confirmation page. Confirmed via sms. On the page I received the answer "OK". But in HA the error still remained, the map is not displayed and after restarting HA again requires to follow the link for autorize.

After that everything was fine to me...

**Comment by gogenzuller** [comment]
> After that everything was fine to me...

Yes, it worked. It's just that my HA connects via VPN to Oracle VPS and it has different IP addresses for incoming and outgoing traffic. At first I tried to authorize from a VPS public IP for incoming connections, but it was necessary from an IP of HA host (for outgoing requests).

**Comment by rvalentinis** [comment]
Same here

**Comment by Rhylthus** [comment]
same here

**Comment by pixeldublu** [comment]
Ok... apparently link works ok just make sure no ad blocker is running :)

After link confirmation and HA restart. Works fine again!🥳

Thanks a lot! 👍

**Comment by diogodias24** [comment]
Same here. I copy paste the URL on logs after 2 minutes of reboot and it open the "Dicas" page.

**Comment by sagitt** [comment]
open it on mobile phone.

**Comment by bellini666** [comment]
Hey guys,

Trying to make this work. I can open the link, validate my login through either phone or email, I get the "ok" screen, but nothing happens on HA. No matter if I wait for some time or force it to reload right after, it still presents me the "open this URL" log the next time it starts.

And yes, I'm on the same public ip as all of my devices.

**Comment by StWiesi** [comment]
> > I have the same problem. Disabled adguard. Restarted HA. Refreshed the page with the log until a message appeared about the need to re-authorize. I immediately opened the link, got to the account confirmation page. Confirmed via sms. On the page I received the answer "OK". But in HA the error still remained, the map is not displayed and after restarting HA again requires to follow the link for autorize.
> 
> After that everything was fine to me...

worked also for me.

**Comment by Pivek** [comment]
Unfortunately, for me two-factor authentication doesn't work as well...

**Comment by gogenzuller** [comment]
> Unfortunately, for me two-factor authentication doesn't work as well

Maybe you need to enable it in your account settings?
![2021-11-04_14-36-15-433](https://user-images.githubusercontent.com/10682203/140307223-1bc4df51-249b-4d99-a7a6-68fd96a9494f.jpg)



> And yes, I'm on the same public ip as all of my devices.

To pass authorization you need:
1. Check if two-factor authentication is enabled in your xiaomi account (I don't know if it's necessary or not)
2. Disable ad blockers and other similar services on the device from which you will be authorized, which can change your ip or http request.
3. Check the ip address of your browser, for example, on the website https://www.myip.com/
4. Check the public ip address of your host with HA for example from the HA console or in SSH & Web Terminal add-on with the bash command 'curl ifconfig.me'
5. If the addresses match, go to the 'Configuration' > 'Server controls' > 'YAML configuration reloading' tab in the HA web interface and click the XIAOMI_CLOUD_MAP_EXTRACTOR button.
You can just restart HA but it takes a long time.
6. Immediately after that, check the log and follow the link from error massage. Apparently, the link works no more than 0.5-1.5 minutes, so this should be done quickly.
7. After that, go through the confirmation of the account in any available way.
8. After confirming, refresh the page with the map, it should appear almost immediately, but there will be no calibration points, so you need to restart HA, everything should work.

**Comment by cubedube** [comment]
hi gogenzuller 

i just did all of your steps and still get no map. tried twice now :(

**Comment by gogenzuller** [comment]
> i just did all of your steps and still get no map. tried twice now :(

Then I don't know how to help. It sound unbelievable, but maybe you have authorized the wrong xiaomi account?

**Comment by Pivek** [comment]
> > i just did all of your steps and still get no map. tried twice now :(
> 
> Then I don't know how to help. It sound unbelievable, but maybe you have authorized the wrong xiaomi account?

It all seems to be very strange. I was able to make that two-factor authentication month ago. Now I just repeated all these steps and simply no success.

**Comment by cubedube** [comment]
i only have one xiaomi account and my old phone is temporary connected to the same account. That works perfect.
Could it be that it only works with a phone number??? i only have a email there.

My plan was to take everything offline cause i dont like to share everything happening at my home .
spent the last night quite some time to configuring all the rooms so i can take the final map offline and today the map is not loading anymore - hehe what a coincident

can anyone confirm that probably that it only works with a phone to reestablish?

i am now that far that i dont get any emails anymore cause i tried that many times i believe.
will give it a try tomorrow again and will let u know

**Comment by gogenzuller** [comment]
> can anyone confirm that probably that it only works with a phone to reestablish?

If, after checking, you were redirected to a page with a single "OK" message, then everything is fine. Maybe checking by e-mail takes more time and the link has time to become outdated? But this is unlikely.

**Comment by cubedube** [comment]
i always got the "OK"

**Comment by bellini666** [comment]
@gogenzuller just tried your exact steps and no success. It get the "ok" page after the login but after refreshing HA I still get the same log and no map :(

**Comment by JaCoLJcL** [comment]
I tried with chrome and allready logged to my xiaomi account and no use :/ I see a "Porady" / "Tips" page .... Hope to get quick fix !

**Comment by diogodias24** [comment]
> 8\. esh the page with the map, it should appear almost immediately, but there will be no calibration points, so you need to restart HA, everything should work.

That got me further on the process. 
I oppened the link in incognito mode really fast after restarting the HA, and successfully validate the 2nd factor. After that received a 'OK', but error persists (Two factor auth required(see logs)). even with a restart on HA and a full restart on host.
Any ideas?

**Comment by gogenzuller** [comment]
Try it without incognito mode

**Comment by gogenzuller** [comment]
Try it without incognito mode

**Comment by bellini666** [comment]
It doesn't work at all. Tried other times, from my desktop (no incognito mode), from my cellphone. When validating my account tried either to receive the code from email and also from phone, with both works and sends me to a page with "ok" in it. Then going back to the map or even trying to restart HA doesn't do anything...

I can't even try anymore because xiaomi said I exceeded the number of times I can do that in 24h.

**Comment by agustusbotti** [comment]
> > Unfortunately, for me two-factor authentication doesn't work as well
> 
> Maybe you need to enable it in your account settings? ![2021-11-04_14-36-15-433](https://user-images.githubusercontent.com/10682203/140307223-1bc4df51-249b-4d99-a7a6-68fd96a9494f.jpg)`
> 
> > And yes, I'm on the same public ip as all of my devices.
> 
> To pass authorization you need:
> 
> 1. Check if two-factor authentication is enabled in your xiaomi account (I don't know if it's necessary or not)
> 2. Disable ad blockers and other similar services on the device from which you will be authorized, which can change your ip or http request.
> 3. Check the ip address of your browser, for example, on the website https://www.myip.com/
> 4. Check the public ip address of your host with HA for example from the HA console or in SSH & Web Terminal add-on with the bash command `curl ifconfig.me`
> 5. If the addresses match, go to the 'Configuration' > 'Server controls' > 'YAML configuration reloading' tab in the HA web interface and click the XIAOMI_CLOUD_MAP_EXTRACTOR button.
>    You can just restart HA but it takes a long time.
> 6. Immediately after that, check the log and follow the link from error massage. Apparently, the link works no more than 0.5-1.5 minutes, so this should be done quickly.
> 7. After that, go through the confirmation of the account in any available way.
> 8. After confirming, refresh the page with the map, it should appear almost immediately, but there will be no calibration points, so you need to restart HA, everything should work.

Worked for me, Thanks!

**Comment by Fannangir** [comment]
Same issue, the method above didn't work.
Receive ok message, but still no map :(.

**Comment by polo1469** [comment]
Same issue, the method above didn't work for me.
Receive ok message, with two-factor authentication, but still no map :(

**Comment by kikofhm** [comment]
I'm with the same problem. From couple days ago the map it's STOP working.

the card shows: "two factor auth required (see logs)"
I restart HA and in logs Additional authentication required. `Open following URL using device that has the same public IP, as your Home Assistant instance: https://account.xiaomi.com/ident... `sometimes the page only shows Mi logo and Tips but nothing more, othertimes I can get the login page fill the form receive the code to my email and the page shows "ok" in left upper corner"

in my mi account in 2 step auth menu it's disable...

**Comment by kaizersoje** [comment]
Same here

**Comment by baggein** [comment]
I went through all the steps and got "Ok", but it still doesn't work ...

**Comment by digitalit** [comment]
Following

**Comment by wanti00** [comment]
Same problem, following

**Comment by vikdb** [comment]
> The Link is only working for short time. After try to catch the Link instantly after a reboot, it was possible to MFA to my phone. Also deactivated my AdGuard-Protection for that time, i dont know if it cares.

This is the FIX!

**Comment by wanti00** [comment]
it help to get map but vacuum card couldnt ger data for remaing time for bursh etc.

**Comment by PiotrMachowski** [comment]
@wanti00 this is a problem with vacuum card, not with this integration

**Comment by Fannangir** [comment]
Tried multiple times, from the phone as well.
Ends up with ok, but integration keeps the same message, unfortunately 😟

**Comment by PiotrMachowski** [comment]
@Fannangir have you tried reloading extractor domain after that?

**Comment by Fannangir** [comment]
I guess you mean XIAOMI_CLOUD_MAP_EXTRACTOR reload.
If this is the meaning, I did. After reload, same message appears, additional authentication required…

**Comment by Subia75** [comment]
Hi, I also have the same problem since the upgrade to 2021.11 I tried a few times to authenticate but it does not load the map.

**Comment by dbloom86** [comment]
Hi, I have the exact same issue. Everything that is mentioned does not work. It has worked before, and it just stopped out of nowhere.

**Comment by stylab** [comment]
following

**Comment by PiotrMachowski** [comment]
@stylab You can do it without adding comments
![image](https://user-images.githubusercontent.com/6118709/140918717-652b987f-1a39-4376-a2a7-59cdd0d4e2bf.png)

**Comment by stylab** [comment]
@PiotrMachowski thanks for the info I did not know that :) always a great day when you learn something new :)

**Comment by PiotrMachowski** [comment]
Time for some cleaning up. There are 3 issues for the same problem (#157, #180, #181), so I will move all discussion to the first one: #157
