### ISSUE TITLE
HA 2021.11 broke this integration

### ISSUE THREAD

**Issue by bellini666** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#183]
Hi,

After updating to 2021.11 this  integration stopped working due to the fact that attribute have been transformed into sensors: https://www.home-assistant.io/blog/2021/11/03/release-202111/#breaking-changes

Maybe this is related and the reason of https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/issues/180 , but I decided to open a new issue in case it isn't related.

**Comment by PiotrMachowski** [comment]
I don't think that's how it works... Every integration has to be changed separately + this integration doesn't use any other entities. Do you have anything in logs?

**Comment by bellini666** [comment]
Oh I see. Ok, my bad then. I think that since everything just happened together I thought it made sense that the update broke this.

So, it seems that I'm suffering from the same issue as #180. I just opened the url in a cellphone and it worked, then I restarted HA and it was still having problems. I'm trying now to wait for it to go back by itself, will report later if it works.
