### ISSUE TITLE
Failed to retrieve model

### ISSUE THREAD

**Issue by ffesius** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#186]
Logger: custom_components.xiaomi_cloud_map_extractor.camera
Source: custom_components/xiaomi_cloud_map_extractor/camera.py:288
Integration: xiaomi_cloud_map_extractor (documentation, issues)
First occurred: 13:03:22 (35 occurrences)
Last logged: 15:06:05

Failed to retrieve model

The integration worked before. Vacuum cleaner Roidmi EVE Plus

**Comment by PiotrMachowski** [comment]
Can you check if token is still valid?

**Comment by gerok1984** [comment]
I have a problem with Roidmi Eve Plus too.
The integration has been working for months
![Screenshot_20211108-144812_Home Assistant](https://user-images.githubusercontent.com/83238357/140753593-ae260074-fa9b-4a48-9108-264d45fc8075.jpg)

**Comment by ffesius** [comment]
Thanks, the token really changed.
