### ISSUE TITLE
s6 maxv

### ISSUE THREAD

**Issue by sagitt** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#19]
i don't know if this is the righe place

you can add "s6 maxv" to your compatibility list.

i'm using it and works fine.

**Comment by PiotrMachowski** [comment]
Vacuum added :)

Unfortunately default font in library I use doesn't support setting size, so font have to be mandatory
Refresh without restart is a hard thing to do, right now you can check available solutions [here](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/issues/6)
