### ISSUE TITLE
iOS rendering issues

### ISSUE THREAD

**Issue by beyondtenor** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#191]
When using the home assistant app on my iPhone, it renders weirdly. The room icons are in the top left corner stacked even though the room names and such as in the correct areas. Also I can select a room to clean, or even a pin and go. But the predefined points icon have the same problem so I can’t choose those. And I can’t draw a path. Maybe this is a configuration issue on my end? Everything works as expected on a computer browser.
![C6A96458-C7CD-4588-BD16-41D2CBC9DB4D](https://user-images.githubusercontent.com/25716286/142739062-e784f885-6e38-4680-b785-0cd48079eb0b.png)

**Comment by PiotrMachowski** [comment]
Wrong repository + duplicate: https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/issues/130
