### ISSUE TITLE
Failed to retrieve model. 

### ISSUE THREAD

**Issue by Silent4831** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#192]
Hey! Please tell me if it gives this error: Failed to retrieve model. My vacuum cleaner model is rockrobo.vacuum.v1
![2021-11-21_15-41-02](https://user-images.githubusercontent.com/37260995/142762247-578da5d1-122e-413e-9f2c-ad9c19f4ab7d.png)
![2021-11-21_15-40-16](https://user-images.githubusercontent.com/37260995/142762251-3b1412ea-180d-4554-b1d6-2ba9d21d1c23.png)
![2021-11-21_15-41-31](https://user-images.githubusercontent.com/37260995/142762255-4b1924ef-1935-4609-a9e8-ad997d47f140.png)

![2021-11-21_15-45-08](https://user-images.githubusercontent.com/37260995/142762447-d5d18d53-e0b1-4e1c-ad69-d4b2115582ed.png)
.

**Comment by PiotrMachowski** [comment]
Try wrapping your token with double quotes. If it doesn't help check if token and IP are the same as returned by [Tokens Extractor](https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor)

**Comment by Silent4831** [comment]
> Try wrapping your token with double quotes. If it doesn't help check if token and IP are the same as returned by [Tokens Extractor](https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor)

I put double quotes, checked the ip and token, everything matches. The map is not loading((

**Comment by PiotrMachowski** [comment]
What is your vacuum model?

**Comment by Silent4831** [comment]
> What is your vacuum model?

rockrobo.vacuum.v1

**Comment by MityaDVG** [comment]
Hello, I have a same error, my model: roborock.vacuum.a15. I have 3 floors maps, maybe this problem?
![Screenshot 2021-11-23 112842](https://user-images.githubusercontent.com/90910957/143000932-16fb6787-8f8a-4504-b525-c8bb633f657b.png)

**Comment by PiotrMachowski** [comment]
@MityaDVG well, your error is definitely not the same. You can try adding following line to your config:
```yaml
force_api: viomi
```
or if this doesn't work:
```yaml
force_api: roidmi
```

**Comment by MityaDVG** [comment]
> @MityaDVG well, your error is definitely not the same. You can try adding following line to your config:
> 
> ```yaml
> force_api: viomi
> ```
> 
> or if this doesn't work:
> 
> ```yaml
> force_api: roidmi
> ```
I try this commands for my config, and have same problem.
![Screenshot 2021-11-23 120051](https://user-images.githubusercontent.com/90910957/143005094-027cb166-a333-40f3-9b37-2362d002ff3a.png)

**Comment by PiotrMachowski** [comment]
Ok, I have checked now and `roborock.vacuum.a15` should work with `xiaomi` API. Please if IP address & token are valid

**Comment by MityaDVG** [comment]
> Ok, I have checked now and `roborock.vacuum.a15` should work with `xiaomi` API. Please if IP address & token are valid
Yes, because manually add vacuum to HA is working
![Screenshot 2021-11-23 121309](https://user-images.githubusercontent.com/90910957/143006226-95bb5277-e43a-4c95-ac93-cf80b429153c.png)

**Comment by PiotrMachowski** [comment]
This is a minor problem which already has been raised (#168)

**Comment by reinethernal** [comment]
HI! Got the same error, but with mijia.vacuum.v2

**Comment by pr0fetul** [comment]
Same error here with roborock s5.

**Comment by Blackpander** [comment]
Same here with the roborock s5.

**Comment by PiotrMachowski** [comment]
@Blackpander today there were some issues with Xiaomi cloud, please try restarting HA and check if error is still there

**Comment by YOZZOPANOZZO** [comment]
Same here with roborock 5 max, could this be related to the recent issues with the  mi home app? 
![Screenshot_20211231-142800](https://user-images.githubusercontent.com/54823311/147836783-ded6b9fe-06dd-4020-b1bb-c4f880c4d57f.jpg)

**Comment by YOZZOPANOZZO** [comment]
Restarting did not solve it unfortunately, it might be a temporary issue though

**Comment by YOZZOPANOZZO** [comment]
I have just noticed that the token shown for the entity camera.xiaomi_cloud_map_extractor in developer option is different from the one in the yaml config, is it normal?

**Comment by PiotrMachowski** [comment]
@YOZZOPANOZZO yes, it seems that it is related. 

This token is HA token for retrieving camera image, so it should be different

**Comment by matata86** [comment]
Same problem ... rockrobo.vakuum.v1

no change after restart .

**Comment by tuplass** [comment]
Seems like there's a problem with Xiaomi's de server. When trying to use [token extractor](https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor) there's a different message for the de server.

> Username (email or user ID):
> xxxxxxxxxxx
> Password:
> xxxxxxxxxxx
> Server (one of: cn, de, us, ru, tw, sg, in, i2) Leave empty to check all available:
> 
> Logging in...
> Logged in.
> 
> No devices found for server "cn".
> Unable to get devices.
> No devices found for server "us".
> No devices found for server "ru".
> No devices found for server "tw".
> No devices found for server "sg".
> No devices found for server "in".
> No devices found for server "i2".
> 
> Press ENTER to finish

**Comment by fritanga** [comment]
Seems the problem is related to an auth change as stated [here](https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor/issues/50)

**Comment by PiotrMachowski** [comment]
@Silent4831 @reinethernal @pr0fetul Does everything work in the latest version?

**Comment by kurim** [comment]
@PiotrMachowski, yes it works again.

**Comment by pr0fetul** [comment]
I can confirm it works.👍

**Comment by reinethernal** [comment]
@PiotrMachowski Not working :( maybe this is because i have not such popular model - mijia.vacuum.v2

**Comment by PiotrMachowski** [comment]
@reinethernal What message is displayed?

**Comment by reinethernal** [comment]
> @reinethernal What message is displayed? (in dev tools)

![image](https://user-images.githubusercontent.com/35932698/147971032-1a21f79d-fe98-4174-aa46-917bfe69d9bc.png)

**Comment by PiotrMachowski** [comment]
And on the camera image?

**Comment by reinethernal** [comment]
@PiotrMachowski 
![image](https://user-images.githubusercontent.com/35932698/147972386-4f90b840-ceb9-49a8-8ec9-072afb2ae414.png)

**Comment by PiotrMachowski** [comment]
You can try adding `force_api: viomi` or `force_api: roidmi`, maybe one of them will work

**Comment by reinethernal** [comment]
Then i should restart all host, or just reload integration?

**Comment by PiotrMachowski** [comment]
Reload should be enough

**Comment by reinethernal** [comment]
Thank you, i'll try it right now)

**Comment by reinethernal** [comment]
Using force_api: viomi i get such image:
![image](https://user-images.githubusercontent.com/35932698/147973089-acdf978e-9b87-49c4-bea8-9d90eca0715a.png)
using force_api: roidmi
![image](https://user-images.githubusercontent.com/35932698/147973343-97151736-355f-45b7-a7bf-e5df3a0319b8.png)
- same

**Comment by PiotrMachowski** [comment]
Ok, let's create a separate issue for this model. Could you please send me a raw map file?
```
store_map_raw: true
store_map_path: "/config"
```
`piotr.machowski.dev [at] gmail.com`

**Comment by reinethernal** [comment]
How can i find it? There's no anything under config folder that can somehow be associated with map((

**Comment by PiotrMachowski** [comment]
You have to do it with `force_api: viomi` or roidmi

**Comment by reinethernal** [comment]
with such a config, I can not get a single file that in any way related to the map
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    name: "Vacuum Camera"
    country: "cn"
#    force_api: xiaomi
#    force_api: viomi (tried both viomi and roidmi)
    force_api: roidmi
#    draw: ['all']
#    scan_interval:
#      seconds: 10
    auto_update: true
    store_map_raw: true
    store_map_path: "/config"
#    attributes:
#     - calibration_points

**Comment by PiotrMachowski** [comment]
Is there anything in logs...?

**Comment by reinethernal** [comment]
> Is there anything in logs...?

when i set up viomi api i receive 
```
2022-01-04 00:26:00 DEBUG (SyncWorker_6) [custom_components.xiaomi_cloud_map_extractor.camera] Retrieved device model: mijia.vacuum.v2
2022-01-04 00:26:00 DEBUG (SyncWorker_6) [custom_components.xiaomi_cloud_map_extractor.camera] Created device, used api: viomi
2022-01-04 00:26:00 DEBUG (SyncWorker_6) [custom_components.xiaomi_cloud_map_extractor.camera] Retrieving map from Xiaomi cloud
2022-01-04 00:26:01 INFO (MainThread) [homeassistant.setup] Setting up script
2022-01-04 00:26:01 INFO (MainThread) [homeassistant.setup] Setup of domain zone took 19.3 seconds
2022-01-04 00:26:02 INFO (MainThread) [homeassistant.setup] Setting up device_tracker
2022-01-04 00:26:02 INFO (MainThread) [homeassistant.setup] Setup of domain script took 1.3 seconds
2022-01-04 00:26:02 INFO (MainThread) [homeassistant.setup] Setup of domain device_tracker took 0.3 seconds
2022-01-04 00:26:02 WARNING (SyncWorker_6) [custom_components.xiaomi_cloud_map_extractor.camera] Unable to retrieve map data
```
when i try to use roismi, i get 
```
2022-01-04 00:33:08 DEBUG (SyncWorker_11) [custom_components.xiaomi_cloud_map_extractor.camera] Retrieved device model: mijia.vacuum.v2
2022-01-04 00:33:08 DEBUG (SyncWorker_11) [custom_components.xiaomi_cloud_map_extractor.camera] Created device, used api: roidmi
2022-01-04 00:33:08 DEBUG (SyncWorker_11) [custom_components.xiaomi_cloud_map_extractor.camera] Retrieving map from Xiaomi cloud
2022-01-04 00:33:10 WARNING (SyncWorker_11) [custom_components.xiaomi_cloud_map_extractor.camera] Unable to retrieve map data
2022-01-04 00:33:14 DEBUG (SyncWorker_15) [custom_components.xiaomi_cloud_map_extractor.camera] Logging in...
```
