### ISSUE TITLE
Failed to retrieve map from vacuum

### ISSUE THREAD

**Issue by sbeagle25** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#194]
My vacuum cleaner model is rockrobo.vacuum.v1
I have tried several times still get error
![螢幕擷取畫面 2021-11-25 005526](https://user-images.githubusercontent.com/15396423/143282564-95bba17e-649c-4d94-97e1-408d921d7a76.jpg)
.
![螢幕擷取畫面 2021-11-25 002803](https://user-images.githubusercontent.com/15396423/143282586-1dd340c0-2a64-4d81-9045-05478320fbc2.jpg)
![螢幕擷取畫面 2021-11-25 002853](https://user-images.githubusercontent.com/15396423/143282598-20b4836e-086c-4a41-bbec-b8164dd417a7.jpg)
I found the token in entity camera.xiaomi_cloud_map_extractor is different from my config where I get from token_extractor.
Once I set the correct token in entity, there is another unknown login trying to login my home assistant. Few seconds later, the token came back to the wrong one.

**Comment by PiotrMachowski** [comment]
This is a different token, it is used to get camera image, it shouldn't be changed. Was map extractor working before?

**Comment by sbeagle25** [comment]
No, I just use this first time.
Is there anything I missed?

**Comment by PiotrMachowski** [comment]
Make sure that token and IP address match values from [Tokens extractor](https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor) (token is case-sensitive!)

**Comment by sbeagle25** [comment]
Sure! 
Both IP address and token are correct.
Is the region of server matters? My device only works in "sg".
It wont work in "cn" server.

**Comment by Yurhik** [comment]
Hello, I also observe such an error. After updating from 2021.11.4 to 2021.21.5.
Token and host are correct.

Logger: custom_components.xiaomi_cloud_map_extractor.camera
Source: custom_components/xiaomi_cloud_map_extractor/camera.py:288
Integration: xiaomi_cloud_map_extractor (documentation, issues)
First occurred: 12:40:30 (191 occurrences)
Last logged: 13:27:43

Failed to retrieve model

**Comment by Swinkey87** [comment]
Same problem here. 
RoboRock S5 died a while ago, then everything was working. 
So I got a new RoboRock S7. 
Now its failing to retreive map from vacuum.

**Comment by sbeagle25** [comment]
I tried to remove the xiaomi integration (miio) and rest several times. Suddenly it works. I guess the server is not stable.

**Comment by rainman369** [comment]
Also having consistent issues with this. Sometimes it works, other times there are a bunch of errors in my log, today the map isn't showing.

**Comment by nkgiovannivl** [comment]
Same situation here, for couple hours the Map extractor does not show info Developer Tools -> camera.xiaomi_cloud_map_extractor, but sundenly starts works normal...

**Comment by ultimate-tester** [comment]
I have the same problem. Today is my first time trying to setup the Xiaomi cloud map extractor. It never worked unfortunately. I was able to successfully extract the token using the "token extractor" tool. Unfortunately it results in the following in the logs:

```
Logger: custom_components.xiaomi_cloud_map_extractor.camera
Source: custom_components/xiaomi_cloud_map_extractor/camera.py:305
Integration: xiaomi_cloud_map_extractor (documentation, issues)
First occurred: 10:32:32 PM (1 occurrences)
Last logged: 10:32:32 PM
Got exception while fetching the state: No response from the device
```


```
Logger: miio.miioprotocol
Source: /usr/local/lib/python3.9/site-packages/miio/miioprotocol.py:240
First occurred: 10:32:32 PM (16 occurrences)
Last logged: 10:37:37 PM
Got error when receiving: timed out
```

**Comment by MrAges** [comment]
Same Problem here. I tried everything but it still wont load the map from the vacuum (cloud). Are there any other suggested solutions than those already mentioned here? 

`2022-01-19 18:37:13 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:20
2022-01-19 18:37:14 DEBUG (SyncWorker_4) [custom_components.xiaomi_cloud_map_extractor.camera] Retrieving map name from device
2022-01-19 18:37:19 DEBUG (SyncWorker_4) [custom_components.xiaomi_cloud_map_extractor.camera] Retrieving map name from device
2022-01-19 18:37:24 DEBUG (SyncWorker_4) [custom_components.xiaomi_cloud_map_extractor.camera] Unable to retrieve map, reasons: Logged in - True, map name - retry, device retrieved - True
2022-01-19 18:37:33 DEBUG (SyncWorker_6) [custom_components.xiaomi_cloud_map_extractor.camera] Retrieving map name from device
2022-01-19 18:37:38 DEBUG (SyncWorker_6) [custom_components.xiaomi_cloud_map_extractor.camera] Retrieving map name from device
2022-01-19 18:37:43 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.my_vacuum_camera is taking over 10 seconds
2022-01-19 18:37:43 DEBUG (SyncWorker_6) [custom_components.xiaomi_cloud_map_extractor.camera] Retrieving map name from device
2022-01-19 18:37:48 DEBUG (SyncWorker_6) [custom_components.xiaomi_cloud_map_extractor.camera] Retrieving map name from device
2022-01-19 18:37:53 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:20
2022-01-19 18:37:53 DEBUG (SyncWorker_6) [custom_components.xiaomi_cloud_map_extractor.camera] Retrieving map name from device
2022-01-19 18:37:58 DEBUG (SyncWorker_6) [custom_components.xiaomi_cloud_map_extractor.camera] Retrieving map name from device`

**Comment by PiotrMachowski** [comment]
@MrAges check if token and IP are correct. They sometimes like to change

**Comment by MrAges** [comment]
I did with token extractor and it seem ok - otherwise "device retrieved - true" would not be in logs right?

**Comment by PiotrMachowski** [comment]
@MrAges actually it means that device model has been retrieved from the cloud. The problem is that your vacuum doesn't respond to calls for map. You can try restarting it, maybe it will help

**Comment by MrAges** [comment]
Restarting the vacuum helps - so easy. Thank you for your support!! Your integration is pretty cool!

**Comment by antstyl** [comment]
I have the same problem here and I get a lot of errors in logs like the image attached.
Vacuum works but cannot load map in anyway
Tokens checked and they are correct (obviously as vacuum works from HA) and have also tried restarting vacuum.

![Screenshot 2022-01-30 115236](https://user-images.githubusercontent.com/6030798/151694970-f4f3a449-f4bb-4575-bb37-809fa4e83ed4.png)
!

**Comment by PiotrMachowski** [comment]
@antstyl Which model do you have?

**Comment by antstyl** [comment]
> @antstyl Which model do you have?

Xiaomi STYTJ02YM (Xiaomi Mi Robot Vacuum Mop P Wi-Fi)

**Comment by PiotrMachowski** [comment]
Can you show your config?

**Comment by antstyl** [comment]
Do you mean how configuration.yaml file is?

Meantime see how card is configured.
![Screenshot 2022-01-30 160050](https://user-images.githubusercontent.com/6030798/151702902-6e0dd546-cfd1-4425-b1fc-552eba43dc65.png)

**Comment by PiotrMachowski** [comment]
Yup

**Comment by antstyl** [comment]
`homeassistant:
# configuration.yaml entry  
  external_url: https://
  internal_url: http://192.168.1.207:8123


# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

vacuum:
  - platform: miio2
    host: 192.168.1.222
    token: 614b6d443366--------------
    name: Mi hihi
    
camera:
  - platform: xiaomi_cloud_map_extractor
    host: 192.168.1.222
    token: 614b6d443366--------------
    username: --------
    password: --------
    country: "de"
    name: "My Vacuum Camera"
    colors:
      color_map_inside: [32, 115, 185]
      color_map_outside: [19, 87, 148]
      color_map_wall: [100, 196, 254]
      color_map_wall_v2: [93, 109, 126]
      color_grey_wall: [93, 109, 126]
      color_ignored_obstacle: [0, 0, 0, 127]
      color_ignored_obstacle_with_photo: [0, 0, 0, 127]
      color_obstacle: [0, 0, 0, 127]
      color_obstacle_with_photo: [0, 0, 0, 127]
      color_path: [147, 194, 238]
      color_goto_path: [0, 255, 0]
      color_predicted_path: [255, 255, 0, 0]
      color_cleaned_area: [127, 127, 127, 127]
      color_zones: [0xAD, 0xD8, 0xFF, 0x8F]
      color_zones_outline: [0xAD, 0xD8, 0xFF]
      color_virtual_walls: [255, 0, 0]
      color_new_discovered_area: [64, 64, 64]
      color_no_go_zones: [255, 33, 55, 127]
      color_no_go_zones_outline: [255, 0, 0]
      color_no_mop_zones: [163, 130, 211, 127]
      color_no_mop_zones_outline: [163, 130, 211]
      color_charger: [0x66, 0xfe, 0xda, 0x7f]
      color_robo: [75, 235, 149]
      color_room_names: [0, 0, 0]
      color_unknown: [0, 0, 0]
      color_scan: [0xDF, 0xDF, 0xDF]
    room_colors:
      1: [240, 178, 122]
      2: [133, 193, 233]
      3: [217, 136, 128]
      4: [52, 152, 219]
      5: [205, 97, 85]
    draw:
      - charger
      - cleaned_area
      - goto_path
      - ignored_obstacles
      - ignored_obstacles_with_photo
      - no_go_zones
      - no_mopping_zones
      - obstacles
      - obstacles_with_photo
      - path
      - predicted_path
      - room_names
      - vacuum_position
      - virtual_walls
      - zones
    map_transformation:
      scale: 2
      rotate: 180
      trim:
        top: 10
        bottom: 20
        left: 30
        right: 40
    sizes:
      charger_radius: 4
      vacuum_radius: 6.5
      obstacle_radius: 3
      ignored_obstacle_radius: 3
      obstacle_with_photo_radius: 3
      ignored_obstacle_with_photo_radius: 3
    attributes:
      - calibration_points
      - charger
      - cleaned_rooms
      - country
      - goto
      - goto_path
      - goto_predicted_path
      - image
      - is_empty
      - map_name
      - no_go_areas
      - no_mopping_areas
      - obstacles
      - ignored_obstacles
      - obstacles_with_photo
      - ignored_obstacles_with_photo
      - path
      - room_numbers
      - rooms
      - vacuum_position
      - vacuum_room
      - vacuum_room_name
      - walls
      - zones
    scan_interval:
      seconds: 10
    auto_update: true
    store_map_raw: false
    store_map_image: true
    store_map_path: "/tmp"
    force_api: xiaomi
    
    
    

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# configuration.yaml entry  
http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: true
  login_attempts_threshold: 5
  
sonoff:
  username: --------
  password: --------
  reload: always
  
switch:
  - platform: xiaomi_miio_plug
    name: Netflix
    host: 192.168.1.59
    token: 35b763e97-----------------
    model: chuangmi.plug.m1
  - platform: xiaomi_miio_plug
    name: Office Power Strip
    host: 192.168.1.58
    token: bd1cced5a-------------------
    model: qmi.powerstrip.v1
  - platform: xiaomi_miio_plug
    name: Corridor Power Strip
    host: 192.168.1.57
    token: fee46886e79-----------------
    model: zimi.powerstrip.v2

climate: !include climate.yaml`

**Comment by antstyl** [comment]
I dont know how to post it so not to take so much space here.. 

`homeassistant:
# configuration.yaml entry  
  external_url: https://
  internal_url: http://192.168.1.207:8123


# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

vacuum:
  - platform: miio2
    host: 192.168.1.222
    token: 614b6d443366--------------
    name: Mi hihi
    
camera:
  - platform: xiaomi_cloud_map_extractor
    host: 192.168.1.222
    token: 614b6d443366--------------
    username: --------
    password: --------
    country: "de"
    name: "My Vacuum Camera"
    colors:
      color_map_inside: [32, 115, 185]
      color_map_outside: [19, 87, 148]
      color_map_wall: [100, 196, 254]
      color_map_wall_v2: [93, 109, 126]
      color_grey_wall: [93, 109, 126]
      color_ignored_obstacle: [0, 0, 0, 127]
      color_ignored_obstacle_with_photo: [0, 0, 0, 127]
      color_obstacle: [0, 0, 0, 127]
      color_obstacle_with_photo: [0, 0, 0, 127]
      color_path: [147, 194, 238]
      color_goto_path: [0, 255, 0]
      color_predicted_path: [255, 255, 0, 0]
      color_cleaned_area: [127, 127, 127, 127]
      color_zones: [0xAD, 0xD8, 0xFF, 0x8F]
      color_zones_outline: [0xAD, 0xD8, 0xFF]
      color_virtual_walls: [255, 0, 0]
      color_new_discovered_area: [64, 64, 64]
      color_no_go_zones: [255, 33, 55, 127]
      color_no_go_zones_outline: [255, 0, 0]
      color_no_mop_zones: [163, 130, 211, 127]
      color_no_mop_zones_outline: [163, 130, 211]
      color_charger: [0x66, 0xfe, 0xda, 0x7f]
      color_robo: [75, 235, 149]
      color_room_names: [0, 0, 0]
      color_unknown: [0, 0, 0]
      color_scan: [0xDF, 0xDF, 0xDF]
    room_colors:
      1: [240, 178, 122]
      2: [133, 193, 233]
      3: [217, 136, 128]
      4: [52, 152, 219]
      5: [205, 97, 85]
    draw:
      - charger
      - cleaned_area
      - goto_path
      - ignored_obstacles
      - ignored_obstacles_with_photo
      - no_go_zones
      - no_mopping_zones
      - obstacles
      - obstacles_with_photo
      - path
      - predicted_path
      - room_names
      - vacuum_position
      - virtual_walls
      - zones
    map_transformation:
      scale: 2
      rotate: 180
      trim:
        top: 10
        bottom: 20
        left: 30
        right: 40
    sizes:
      charger_radius: 4
      vacuum_radius: 6.5
      obstacle_radius: 3
      ignored_obstacle_radius: 3
      obstacle_with_photo_radius: 3
      ignored_obstacle_with_photo_radius: 3
    attributes:
      - calibration_points
      - charger
      - cleaned_rooms
      - country
      - goto
      - goto_path
      - goto_predicted_path
      - image
      - is_empty
      - map_name
      - no_go_areas
      - no_mopping_areas
      - obstacles
      - ignored_obstacles
      - obstacles_with_photo
      - ignored_obstacles_with_photo
      - path
      - room_numbers
      - rooms
      - vacuum_position
      - vacuum_room
      - vacuum_room_name
      - walls
      - zones
    scan_interval:
      seconds: 10
    auto_update: true
    store_map_raw: false
    store_map_image: true
    store_map_path: "/tmp"
    force_api: xiaomi
    
    
    

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# configuration.yaml entry  
http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: true
  login_attempts_threshold: 5
  
sonoff:
  username: --------
  password: --------
  reload: always
  
switch:
  - platform: xiaomi_miio_plug
    name: Netflix
    host: 192.168.1.59
    token: 35b763e97-----------------
    model: chuangmi.plug.m1
  - platform: xiaomi_miio_plug
    name: Office Power Strip
    host: 192.168.1.58
    token: bd1cced5a-------------------
    model: qmi.powerstrip.v1
  - platform: xiaomi_miio_plug
    name: Corridor Power Strip
    host: 192.168.1.57
    token: fee46886e79-----------------
    model: zimi.powerstrip.v2

climate: !include climate.yaml`

**Comment by PiotrMachowski** [comment]
Readme explicitly says that you *shouldn't* copy full example. Please use recommended one

**Comment by antstyl** [comment]
I had tried in the past to use only the recommended and because it wasn't working I then tried the full one a little bit ediited.

Now I am using this

camera:
  - platform: xiaomi_cloud_map_extractor
    host: 192.168.1.222
    token: 614b6d443366-------------
    username: 
    password: 
    country: "de"
    draw: ['all']
    attributes:
      - calibration_points`

**Comment by PiotrMachowski** [comment]
Are you sure you should use `de` server? Can you check logs now?

**Comment by antstyl** [comment]
yes de is the correct and after a restart i still see these
![Screenshot 2022-01-30 165732](https://user-images.githubusercontent.com/6030798/151704971-8c1eb8e7-2d27-4247-a536-e72859e7e3c2.png)

![Untitled](https://user-images.githubusercontent.com/6030798/151705029-ccc4d8f3-ad2c-4824-954d-f78e85750c42.jpg)

**Comment by PiotrMachowski** [comment]
there should be more info when you click on the first error

**Comment by antstyl** [comment]
This is what I get when I click the first error:

This error originated from a custom integration.

Logger: homeassistant.helpers.entity
Source: custom_components/xiaomi_cloud_map_extractor/viomi/map_data_parser.py:313
Integration: xiaomi_cloud_map_extractor (documentation, issues)
First occurred: 4:56:38 PM (426 occurrences)
Last logged: 5:32:12 PM

Update for camera.xiaomi_cloud_map_extractor fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 487, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 699, in async_device_update
    await task
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 261, in update
    self._handle_map_data(map_name)
  File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 318, in _handle_map_data
    map_data, map_stored = self._device.get_map(map_name, self._colors, self._drawables, self._texts,
  File "/config/custom_components/xiaomi_cloud_map_extractor/common/vacuum.py", line 28, in get_map
    map_data = self.decode_map(response, colors, drawables, texts, sizes, image_config)
  File "/config/custom_components/xiaomi_cloud_map_extractor/viomi/vacuum.py", line 15, in decode_map
    return MapDataParserViomi.parse(unzipped, colors, drawables, texts, sizes, image_config)
  File "/config/custom_components/xiaomi_cloud_map_extractor/viomi/map_data_parser.py", line 157, in parse
    MapDataParserViomi.parse_section(buf, 'unknown2', map_id)
  File "/config/custom_components/xiaomi_cloud_map_extractor/viomi/map_data_parser.py", line 313, in parse_section
    raise ValueError(
ValueError: error parsing section unknown2 at offset 0x9c4cc: magic check failed. Magic: 0x700c00fe, Map ID: 0x0

**Comment by antstyl** [comment]
After a few more restarts of the HA and the vacuum it now works!!

Thanks for your support
