### ISSUE TITLE
Camera Entity Attributes 

### ISSUE THREAD

**Issue by almostserious** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#2]
First I have to say: Amazing work so far! Exactly what I and I assume many others always wanted.

Now, one question wrt to the entity state attributes that are created within HomeAssistant.
Is it possible to hide things like the path from the attributes, while still being able to see the path on the picture?

I guess this is not possible, since the camera image is actually calculated from the values, correct?

Why I am asking: When going to my developer tools / state, I have to scroll a long time down, until this entity is passed. 
However, this is simply a thing Id like to understand and isn't really an issue per se. 

Again, Great work! Looking forward to the further developments of this addon :)

**Comment by PiotrMachowski** [comment]
Attributes are not required to draw elements of map. They will be used in my [map card](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card).

You are right, so much scrolling is inconvenient, I will make them configurable.

**Comment by PiotrMachowski** [comment]
And it's done! See: [Attributes configuration](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#attributes-configuration)
