### ISSUE TITLE
Room colors not correct (adjacent rooms have same color)

### ISSUE THREAD

**Issue by mindgam3s** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#205]
Hi, 

as stated above some rooms got the same color so you cannot distinguish between them. 

![image](https://user-images.githubusercontent.com/34487011/146616678-fad79beb-7448-4cd3-a40c-71e2c78d94d9.jpeg)

the WHITE lines drawn by hand show where rooms should be separated and have different color.

**Comment by PiotrMachowski** [comment]
You can override default colors if they don't suit your map

**Comment by mindgam3s** [comment]
thanks! didn't realize that. but it's a big anyways. but I'm fine with closing it.
