### ISSUE TITLE
dreame.vacuum.p2041o is not supported ?

### ISSUE THREAD

**Issue by siminkuv** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#208]
I tried to integrate Xiaomi xiaomi vacuum mop 2 pro + Unfortunately HomeAssistant shows me an error message "dreame.vacuum.p2041o is not supported"

![image](https://user-images.githubusercontent.com/81320257/147405621-d9e42b51-63e4-44b9-85e9-a74226d51367.png)

**Comment by PiotrMachowski** [comment]
Duplicate of #126
