### ISSUE TITLE
Break after last HA Update

### ISSUE THREAD

**Issue by thorrrr** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#212]
HI Guys
Error after last update of HA
This error originated from a custom integration.

Home Assistant 2021.12.7
Version | core-2021.12.7

See issue [here ](https://xbackbone.daddycloud.co.uk/Piqa4/muNEDAWE93.jpg)
Logger: custom_components.xiaomi_cloud_map_extractor.camera
Source: custom_components/xiaomi_cloud_map_extractor/camera.py:288
Integration: xiaomi_cloud_map_extractor (documentation, issues)
First occurred: 12:30:09 (995 occurrences)
Last logged: 15:15:59
Failed to retrieve model

**Comment by tbkon3** [comment]
same error

**Comment by andyz68** [comment]
same issue for me

**Comment by kurim** [comment]
HA is not the issue, it caused by the outage of Xiaome Servers.
Already mentioned here: https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/issues/192#issuecomment-1003572574

**Comment by thorrrr** [comment]
Cheers for update
