### ISSUE TITLE
Invalid calibration, please check the configuration

### ISSUE THREAD

**Issue by amastrogiacomo1968** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#218]
I have had this error for a few days

```
This error originated from a custom integration.

Logger: custom_components.xiaomi_cloud_map_extractor.camera
Source: custom_components/xiaomi_cloud_map_extractor/camera.py:288
Integration: xiaomi_cloud_map_extractor (documentation, issues)
First occurred: 2:44:49 PM (379 occurrences)
Last logged: 3:48:24 PM

Failed to retrieve model
```
Obviously the configuration has not changed, I tried to do the configuration from scratch but without the desired result

**Comment by PiotrMachowski** [comment]
Have you updated to the latest release?

**Comment by amastrogiacomo1968** [comment]
I have 2.0.8 , I think it's the last

**Comment by PiotrMachowski** [comment]
https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/releases/tag/v2.1.3

**Comment by amastrogiacomo1968** [comment]
Thanks, I solved it by manually installing the update (HACS does not report the latest release)

**Comment by PiotrMachowski** [comment]
It does, but it takes some time. You can trigger it manually as well

**Comment by amastrogiacomo1968** [comment]
thks :-)

**Comment by AlfaJackal** [comment]
Same here with 2.1.5 on latest HA and HACS. Any ideas?

**Comment by PiotrMachowski** [comment]
@AlfaJackal restart your vacuum

**Comment by AlfaJackal** [comment]
> @AlfaJackal restart your vacuum

Hmm. Did that by pressing reset button and entered my Wifi credentials again as well as extracting a new token. Same result.

**Comment by PiotrMachowski** [comment]
What do you have in logs?

**Comment by AlfaJackal** [comment]
> What do you have in logs?

Thanks for your reply!

![image](https://user-images.githubusercontent.com/17096950/154801897-78fb2235-0536-412c-a53b-c9d915865257.jpeg)

**Comment by PiotrMachowski** [comment]
Can you provide details of the middle one? First and last one don't break anything

**Comment by AlfaJackal** [comment]
Here is the detailed log:
```

This error originated from a custom integration.

Logger: custom_components.xiaomi_cloud_map_extractor.camera
Source: custom_components/xiaomi_cloud_map_extractor/camera.py:337 
Integration: xiaomi_cloud_map_extractor (documentation, issues) 
First occurred: 4:01:57 AM (14 occurrences) 
Last logged: 12:59:39 PM

Unable to retrieve map data

```

**Comment by PiotrMachowski** [comment]
Was everything working before?

**Comment by AlfaJackal** [comment]
I can see the map in HA. What I don't see (and never have seen) are the driving lanes on the map.

**Comment by PiotrMachowski** [comment]
🤦‍♂️  use [recommended config](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#recommended), everything will be shown

**Comment by AlfaJackal** [comment]
I have everything configured and triple checked credentials and token:
![image](https://user-images.githubusercontent.com/17096950/154816163-92594261-5975-44cb-ba39-49d8e96cf979.jpeg)

![image](https://user-images.githubusercontent.com/17096950/154816169-3fc5f3ee-b539-4ac7-9c1f-20f443ee6dcc.jpeg)

**Comment by AlfaJackal** [comment]
> 🤦‍♂️  use [recommended config](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#recommended), everything will be shown 

Indeed! I had not seen that! 🙄 Thank you!
