### ISSUE TITLE
Support for dreame.vacuum.p2041o

### ISSUE THREAD

**Issue by Jezze83** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#221]
![vacuum](https://user-images.githubusercontent.com/10639795/149620804-e9d71b3d-8078-48e8-ac28-d48663f23080.JPG)

So this model not supported? Is it possible get it working?

**Comment by PiotrMachowski** [comment]
Duplicate of #126
