### ISSUE TITLE
Floor Plan Support as background on map

### ISSUE THREAD

**Issue by dmr1987** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#224]
1. Added floor plan support
2. New config values
bg_image_use: true
bg_image_path: '/config/www/map_tmp.png'
bg_image_alpha: 100
3. New draw value
'bg_image'

Fork:
https://github.com/dmr1987/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/

Please merge with master.
Tested with Viomi vacuum

**Comment by PiotrMachowski** [comment]
I plan to add a support for image background, but this is not a correct way to do it, it needs to be calibrated
