### ISSUE TITLE
Card very pixelated due to low resolution

### ISSUE THREAD

**Issue by kimme1024** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#225]
When showing my map on my tablet dashboard the result it shows is very pixelated. A bit like overzooming a low resolution image.
Is there a way to fix this? Higher resolution,...
<img width="931" alt="Schermafbeelding 2022-01-19 om 17 14 12" src="https://user-images.githubusercontent.com/42653485/150170628-1cf4ea2f-4dac-45d5-ad30-c7e52c9f5a45.png">
?

**Comment by PiotrMachowski** [comment]
It's possible, you just have to configure `scale`:
```yaml
map_transformation:
  scale: 2
```
