### ISSUE TITLE
How can I create 2 cards from 2 different vacuum robots?

### ISSUE THREAD

**Issue by kaelsaes** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#227]
Hi,

I installed this amazing integration without any problems. Thanks for your great work.

Now I would like to add our second vacuum robot.

What do I have to add to the configuration.yaml?

Thanks

**Comment by PiotrMachowski** [comment]
https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/discussions/108
