### ISSUE TITLE
Always showing „idle“ 

### ISSUE THREAD

**Issue by kaelsaes** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#228]
Hi,

my vacuum map card always shows „idle“ even if the robot is cleaning.

Regards Kai

**Comment by ildar170975** [comment]
Mine too (Roborock S5).
What if the "idle" status is a normal status for a vacuum's camera?)))

**Comment by kaelsaes** [comment]
Maybe it's possible to delete the status?

**Comment by PiotrMachowski** [comment]
"idle" status means that the camera is not recording nor streaming, do it is an expected value.
