### ISSUE TITLE
[Swipe Card conflict] Touch edit Areas not possible on iOS

### ISSUE THREAD

**Issue by gotschi** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#231]
Hey,

I used this for a long time and just discovered that it causes issues with the touch selection on iOS:
https://github.com/bramkragten/swipe-card

(buttons all work fine, manually resizing areas does not, just zooms in/out on the map)

don't know if this is a issue with your card or swipe card. lmk if i should make bram aware of it.

thanks

**Comment by PiotrMachowski** [comment]
Please create an issue in a correct repository: https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card
