### ISSUE TITLE
Xiaomi vacuum battery level available?

### ISSUE THREAD

**Issue by kaelsaes** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#235]
Hi,

thanks for the great lovelace card.

Is it possible to show the battery level of a vacuum robot?

Regards

**Comment by PiotrMachowski** [comment]
Hi!

This is not a lovelace card, this is a map camera. Lovelace card is available [here](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card) and it shows battery level by default.
