### ISSUE TITLE
Roborock S7: Map is not updated when change is made in Mi Home app.

### ISSUE THREAD

**Issue by Dillton** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#237]
Hello, 
I got my Roborock S7 few days ago and I ma trying to improve my lovelace dashboard with Map card however I am not able to force the map update when I do some change in Mi Home app (for example divide rooms which is now the topic). 

On the screen below you can see there is Hall and Bedroom divien in Mi Home app but not in map card.
Mi Home:
![Mi Home](https://user-images.githubusercontent.com/68992112/152546949-925fe819-559f-4fbd-b995-4f2511ee67cb.png)

Home Assistant:
![image](https://user-images.githubusercontent.com/68992112/152546866-31654d82-87bf-4a8a-b627-13f9942a907b.png)

HA service xiaomi_cloud_map_extractor: Reload did not help.
Do you have any idea?

**Comment by PiotrMachowski** [comment]
It's possible that rooms are updated, just room colors stayed the same. You can check it out by adding "rooms" in "attributes" section

**Comment by Dillton** [comment]
Rooms are already added in attributes.

**Comment by PiotrMachowski** [comment]
Ok, so there are separate numbers available?

**Comment by Dillton** [comment]
Ok nevermind I am just stupid on Friday after work :DD Problem was in room IDs, they are for some reason 16-23 and I automatically thought it is 1-8 (same as in Mi Home app):
![image](https://user-images.githubusercontent.com/68992112/152570756-2703fa8a-d506-496f-8aa3-3c8f217fc327.png)

However thank you for involving and have a nice weekend ;)

**Comment by Dillton** [comment]
Sorry to bother again but one last thing. There is a custom selected zone to clean which persisted after unsuccesful cleanup:
![image](https://user-images.githubusercontent.com/68992112/152578627-f0500482-2ccb-47d1-a950-83b8c5073aeb.png)

How can I get rid of this? :)

**Comment by Dillton** [comment]
Ok agan nevermind its working differently than I thought. See ya. :D

**Comment by PiotrMachowski** [comment]
:D happy to help
