### ISSUE TITLE
Question about calibrate point..

### ISSUE THREAD

**Issue by alesoft73** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#25]
I have integrate a camera.
with this trim:

    map_transformation:
      scale: 1
      trim:
        top: 10
        bottom: 10
        left: 20
        right: 20

But my question is, if i use xiaomi-vacuum-map-card with cam , for  calibrate point ? ( i have  use your flole.xlsx, but don't work)
Becouse map is trasform with trim in home assisitant and i don't have a real point for calibration_point.
Many thanks.
Your work is superlative ;)

**Comment by PiotrMachowski** [comment]
You just have to use calibration from camera's attributes. Documentation how to enable it [link](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#attributes-configuration)
