### ISSUE TITLE
Support request: ijai.vacuum.v3 

### ISSUE THREAD

**Issue by kemendib** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#251]
Dear Piotr,

Could you make support for ijai.vacuum.v3 ? That's sold under the name of Xiaomi Vacuum Mop Pro2 in Hungary. I was using your card with my old Gen1 vacuum and I am amazed by your work! I would love to use this card with my new vacuum!

Thank you in advance for any help!

**Comment by antoweb** [comment]
+1
Thanks

**Comment by evenywchen** [comment]
+1 thanks.

Mi Robot Vacuum-Mop 2 Pro | MJST1SHW
Model: [ijai.vacuum.v3](https://home.miot-spec.com/s/ijai.vacuum.v3)

**Comment by mariusnauj** [comment]
+1
Thanks

**Comment by mariusnauj** [comment]
Maybe somebody know when this device will be supported?

**Comment by PiotrMachowski** [comment]
@mariusnauj I don't think it will be supported anytime soon

**Comment by mariusnauj** [comment]
@PiotrMachowski why ? :)

**Comment by PiotrMachowski** [comment]
Adding support for a new platform is not so easy and I don't have time to do it

**Comment by kemendib** [comment]
I know, I understand... And are you planning on trying it later, or we can give up hoping this? Several of the newer vacuums are using this platform, so making the support for it would mean a lot of models.

**Comment by PiotrMachowski** [comment]
I do not plan it at this moment, maybe someday

**Comment by PiotrMachowski** [comment]
Moving this thread to an earlier one: #200
