### ISSUE TITLE
Map load ok, but actual cleaning not show robot route

### ISSUE THREAD

**Issue by matata86** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#26]
Hi, The current map image is loading properly. But I don't see the actual route and location of the robot. Can you help me please?

**Comment by PiotrMachowski** [comment]
Everything is in [documentation](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#draw-configuration)
