### ISSUE TITLE
There is no option to select a setting.

### ISSUE THREAD

**Issue by Adelich27** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#260]
I just can't choose anything
![Screenshot_1](https://user-images.githubusercontent.com/36339523/158059346-63acabf4-f120-4536-9d0e-2cf53293672c.png)

core-2022.3.3
Home Assistant OS

**Comment by PiotrMachowski** [comment]
Wrong repo

**Comment by PiotrMachowski** [comment]
Releated issue: https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/issues/365
