### ISSUE TITLE
Platform not found

### ISSUE THREAD

**Issue by Anisse4** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#27]
Hi,

Thanks a lot for your development, I'm already using the map card with cleared zone so thank you.
I would like to add the live map in the previous card without rooting the vacuum, so I'm trying to use this map extractor.

I have added in my configuration.yaml the configuration:

camera:
  - platform: xiaomi_cloud_map_extractor
    host: 192.168.1.83
    token: 643162304c785a4b65585a30684b4c4c
    username: mymihome@email
    password: mypasswordmihome
    country: "de"

I have tried to copy past the Github folder "xiaomi_cloud_map_extractor" everywhere but it is not found. 
Have tried these differents path:

/home/homeassistant/.homeassistant/custom_components/xiaomi_cloud_map_extractor
/home/homeassistant/.homeassistant/www/custom_components/xiaomi_cloud_map_extractor

in the folder I have copied these files:

camera.py
const.py
image_handler.py
manifest.json
map_data_parser.py
xiaomi_cloud_connector.py

All files and directory are with homeassistant owner.

What am I missing please ?
Thanks for your help

**Comment by Anisse4** [comment]
I have managed to install it through HACS, I'm moving on, now the custom component is working.
I thing I have add the camera platform in configuration.yaml before restarting HA.

However still blocked, I have this following issue:


Platform error: camera
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/config.py", line 804, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/loader.py", line 322, in get_platform
    f"{self.pkg_path}.{platform_name}"
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/xiaomi_cloud_map_extractor/camera.py", line 8, in <module>
    from .xiaomi_cloud_connector import XiaomiCloudConnector
  File "/home/homeassistant/.homeassistant/custom_components/xiaomi_cloud_map_extractor/xiaomi_cloud_connector.py", line 12, in <module>
    from .map_data_parser import MapDataParser
  File "/home/homeassistant/.homeassistant/custom_components/xiaomi_cloud_map_extractor/map_data_parser.py", line 4, in <module>
    from .image_handler import ImageHandler
  File "/home/homeassistant/.homeassistant/custom_components/xiaomi_cloud_map_extractor/image_handler.py", line 2, in <module>
    from PIL import Image, ImageDraw, ImageFont
  File "/srv/homeassistant/lib/python3.7/site-packages/PIL/Image.py", line 94, in <module>
    from . import _imaging as core
ImportError: libopenjp2.so.7: cannot open shared object file: No such file or directory

**Comment by Anisse4** [comment]
Just fixed it by sudo apt-get install libopenjp2-7 :)

Thanks you again !

**Comment by PiotrMachowski** [comment]
No problem 👍 I'm happy you got it working

PS I hope that it isn't your real token ;)

**Comment by daydrem976** [comment]
Hi. I don't know if a can re-open this topic.
I've the same issue.

When i add Platform code, during check configuration, system relay an error:

Invalid Confiuration 

Platform error vacuum.xiaomi_cloud_map_extractor - No module named 'custom_components.xiaomi_cloud_map_extractor.vacuum'


Here my configuration.yaml ( in bold code rows that i added)
Host, token, username e password are proper

vacuum:
  - platform: xiaomi_miio
    host: 192.168.xxx.xxx
    token: 01010101010101010101010101010101
    name: Rocco
    camera:
  **- platform: xiaomi_cloud_map_extractor
    host: 192.168.xxx.xxx
    token: 01010101010101010101010101010101
    username: xxxxxxxxxx@xxx.xxx
    password: xxxxxxxxxxxxxxxxxxx
    draw: ['all']
    attributes:
      - calibration_points**   


Please, help me to understand what i wrong in my configuration.
I'm not very expert about code compiling.

Thank you very much

**Comment by daydrem976** [comment]
Just a thing.

Files are properly copied in the correct directory.
Thanks in advance

**Comment by PiotrMachowski** [comment]
```
vacuum:
  - platform: xiaomi_miio
    host: 192.168.xxx.xxx
    token: 01010101010101010101010101010101
    name: Rocco
camera:
  - platform: xiaomi_cloud_map_extractor
    host: 192.168.xxx.xxx
    token: 01010101010101010101010101010101
    username: xxxxxxxxxx@xxx.xxx
    password: xxxxxxxxxxxxxxxxxxx
    draw: ['all']
    attributes:
      - calibration_points
 ```

**Comment by daydrem976** [comment]
Hi Piotr,

i'm forget to tell you thanks.
Your solution worked!

Bye

Marino

Il giorno dom 31 gen 2021 alle ore 15:06 Piotr Machowski <
notifications@github.com> ha scritto:

**Comment by Renechr** [comment]
Hi

I can't get this to work, i got the camera entity showing up, but when i try to make a new card with the map, i get this problem. 
Missing property: entity
type: custom:xiaomi-vacuum-map-card

Anyone who has a solution to this?
I'm very new at this

Thanks in advance

**Comment by PiotrMachowski** [comment]
@Renechr I suggest using UI editor to create this card

**Comment by Renechr** [comment]
@PiotrMachowski  thanks, but is there a template for that? i wouldn't even know where to start.

**Comment by PiotrMachowski** [comment]
Install it using HACS and configure it using UI editor (it should be on the bottom)
