### ISSUE TITLE
[Note] Plugin appears to work fine for S7 MaxV

### ISSUE THREAD

**Issue by sgrochowski** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#272]
Hello- Just want to note that the S7 MaxV was released in US just a few days ago, and I have been able to confirm that this plugin does work for the robot. 

Only issue that I had was that the MI Home Token for the S7 MaxV doesn't appear to have letters in it so I had to throw quotations around my token in my secrets file.

Does not currently appear to be pulling photo data from the robot on the obstacles but I am attempting to troubleshoot. 
![image](https://user-images.githubusercontent.com/89114286/162669236-ba9d6ff5-0aab-47db-8b0a-450e7d6fc593.png)

EDIT: Device shows up as an "A27", for updating your documentation.

**Comment by PiotrMachowski** [comment]
Thanks! Documentation updated
