### ISSUE TITLE
Latest HA error on reboot

### ISSUE THREAD

**Issue by thorrrr** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#276]
I keep seeing this error on reboot of HA never had it before. Not sure if it is this card or not 

This error originated from a custom integration.

Logger: custom_components.hacs
Source: custom_components/hacs/tasks/base.py:34
Integration: HACS (documentation, issues)
First occurred: 11:38:39 (1 occurrences)
Last logged: 11:38:39

<HacsTask prosess_queue> failed: <Integration r-renato/hass-xiaomi-mi-flora-and-flower-care> Repository has been requested to be removed.

I also still see this as a warning 

Logger: homeassistant.helpers.entity
Source: helpers/entity.py:745
First occurred: 11:38:16 (1 occurrences)
Last logged: 11:38:16

Update of camera.xiaomi_cloud_map_extractor is taking over 10 seconds

**Comment by PiotrMachowski** [comment]
This one is not from my integration

> This error originated from a custom integration.
> 
> Logger: custom_components.hacs Source: custom_components/hacs/tasks/base.py:34 Integration: HACS (documentation, issues) First occurred: 11:38:39 (1 occurrences) Last logged: 11:38:39
> 
> failed: <Integration r-renato/hass-xiaomi-mi-flora-and-flower-care> Repository has been requested to be removed.
