### ISSUE TITLE
Login attempt or request with invalid authentication

### ISSUE THREAD

**Issue by geniuswebsk** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#280]
Hello all,
I have an issue with warning messages in my log file. It started to appear once I've installed Xiaomi cloud map extractor and added "camera" entity into my configuration.yaml file.
I am using iOS Home assistant app and each time I log in to that app, warning message appears in my log:

Logger: homeassistant.components.http.ban
Source: components/http/ban.py:125
Integration: HTTP (documentation, issues)
First occurred: May 2, 2022, 7:48:11 PM (20 occurrences)
Last logged: 11:00:46 AM

Login attempt or request with invalid authentication from <MY PUBLIC IP ADDRESS>. (Mozilla/5.0 (iPhone; CPU iPhone OS 15_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Home Assistant/2022.3 (io.robbie.HomeAssistant; build:2022.358; iOS 15.4.1) Mobile/HomeAssistant, like Safari)

Could you please help me how to get rid of it?
Thank you.

**Comment by PiotrMachowski** [comment]
It's a problem with the map card
https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/issues/357
