### ISSUE TITLE
wrong depiction among map

### ISSUE THREAD

**Issue by ferropolis** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#282]
Good afternoon, 
I have some wrong depiction among my map.

![2022-05-08 00_18_02-Übersicht – Home Assistant](https://user-images.githubusercontent.com/77990395/167273571-d4fe6c9e-9b6d-43bd-b3ed-9f8c2929aa1c.png)

Version: v2.1.5
Home Assistant Core 2022.5.2
Home Assistant Supervisor 2022.05.0

**Comment by PiotrMachowski** [comment]
https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/issues/365
