### ISSUE TITLE
How to get the map as rrmap

### ISSUE THREAD

**Issue by mnayef95** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#283]
I'm trying to read the map using this application https://community.openhab.org/t/xiaomi-vacuum-map-viewer-to-find-coordinates-for-zone-cleaning/103500/21?page=3

The application is required the map to be `rrmap` or `gz` but this integration is saving the map as zlib which is not readable by the application.

Any idea on how to save the map as zlib?

**Comment by PiotrMachowski** [comment]
`rrmap` files are created by vacuums that use "Xiaomi" API. Viomi maps are stored as `zlib` and they can't be opened with RoboMapViewer
