### ISSUE TITLE
Request support for a new device Thank you

### ISSUE THREAD

**Issue by Bladwintweak** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#288]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the vacuum/platform is already requested
- [ ] I have sent raw map file to `piotr.machowski.dev [at] gmail.com` ([Retrieving map](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#retrieving-map); please provide your GitHub username in the email)

### What vacuum model do you want to be supported?

dreame.vacuum.p2149o

### What is its name?

米家免洗扫地机器人Pro

### Available APIs

- [X] xiaomi
- [ ] viomi
- [ ] roidmi
- [ ] dreame

**Comment by PiotrMachowski** [comment]
I'm not sure what you mean, do you just want to notify that your model works with current version?
