### ISSUE TITLE
Cannot see the component in Integrations

### ISSUE THREAD

**Issue by pr0fetul** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#29]
Hi, first of all - awesome work here. 
I have HA 116.4 - I have added in HACS the repository as per readme - I then installed it and rebooted HA. After loading, when I go to Integrations, I cannot find the Xiaomi Cloud Map Extractor component. 
What I tried was to add the configuration directly in configuration.yaml - and then in HA Frontend I added the camera (camera.r2d2_camera) but it does not show anything. 

Any idea what I am doing wrong?

![camera](https://user-images.githubusercontent.com/17175289/96878495-99e31700-1483-11eb-9816-1fe5012752e6.JPG)
![homeassistant - custom components](https://user-images.githubusercontent.com/17175289/96878499-9b144400-1483-11eb-92fb-582811c98805.JPG)
![configuration yaml](https://user-images.githubusercontent.com/17175289/96878500-9bacda80-1483-11eb-9e27-a767abd9609d.JPG)

Thank you very much

**Comment by PiotrMachowski** [comment]
It is available in integrations, because it doesn't have config flow implemented.

It seems like you have some problems with config, there should be some more info in logs.

**Comment by pr0fetul** [comment]
Thank you for the fast reply. In the logs I found this:
```
Logger: homeassistant.helpers.entity
Source: /usr/local/lib/python3.8/asyncio/events.py:81
First occurred: 4:47:30 PM (3 occurrences)
Last logged: 4:48:33 PM

Update of camera.r2d2_camera is taking over 10 seconds
Update of sensor.opensky is taking over 10 seconds
```
and this - which I think it's normal:
```
Logger: homeassistant.loader
Source: loader.py:440
First occurred: 4:47:17 PM (1 occurrences)
Last logged: 4:47:17 PM

You are using a custom integration for xiaomi_cloud_map_extractor which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
Home Assistant has started!
```

**Comment by pr0fetul** [comment]
I think I might have found the culprit - in the configuration.yaml - there are a few options - 
```
scan_interval:
    seconds: 10
auto_update: true
```
which I took out - restarted HA and the picture populated
I also took out texts: - and I will see what happens

**Comment by pr0fetul** [comment]
Ok, re-inserted scan and texts, and now it renders ok. I do not know what happened. It works now

**Comment by PiotrMachowski** [comment]
that's great :)
