### ISSUE TITLE
Support for Roidmi EVA

### ISSUE THREAD

**Issue by Pepeanuts** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#295]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the vacuum/platform is already requested
- [ ] I have sent raw map file to `piotr.machowski.dev [at] gmail.com` ([Retrieving map](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#retrieving-map); please provide your GitHub username in the email)

### What vacuum model do you want to be supported?

roidmi.vacuum.v66

### What is its name?

Roidmi EVA

### Available APIs

- [ ] xiaomi
- [ ] viomi
- [X] roidmi
- [ ] dreame

### Other info

No action for this model, only the map

![image](https://user-images.githubusercontent.com/73701866/171031909-cbb90598-bd45-4847-a89f-9ce451eef606.png)

**Comment by PiotrMachowski** [comment]
https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card
