### ISSUE TITLE
Calibration points and rooms

### ISSUE THREAD

**Issue by darkkatarsis** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#30]
Hey, I'm just testing a new add-on. Generally it works very well although I am not sure about the accuracy of the calibration. Below are a few screens:

Addon attributes:
<img width="375" alt="Screenshot 2020-10-24 at 16 00 24" src="https://user-images.githubusercontent.com/24244919/97083704-4bb04e00-1612-11eb-8bfb-f43537b5dbca.png">
My settings:
<img width="495" alt="Screenshot 2020-10-24 at 15 59 45" src="https://user-images.githubusercontent.com/24244919/97083718-6256a500-1612-11eb-8b36-2038a8093d11.png">
<img width="318" alt="Screenshot 2020-10-24 at 15 59 53" src="https://user-images.githubusercontent.com/24244919/97083724-64b8ff00-1612-11eb-8675-8b233eb2f0f0.png">
View:
<img width="401" alt="Screenshot 2020-10-24 at 16 03 38" src="https://user-images.githubusercontent.com/24244919/97083741-80bca080-1612-11eb-982f-06f12bb3bdcd.png">

Looks like the rooms have been moved outside the center of the map. Is it because of scaling and triming the map?

**Comment by PiotrMachowski** [comment]
Can you also provide a screenshot from Xiaomi Home app?

**Comment by darkkatarsis** [comment]
No problem:
![IMG_0406](https://user-images.githubusercontent.com/24244919/97084032-68e61c00-1614-11eb-9989-13d7aad6b088.PNG)

Ps. after comment **map_transformation** settings, seems that cords start working fine (I'm still debugging and looking for cousing):
<img width="401" alt="Screenshot 2020-10-24 at 16 18 19" src="https://user-images.githubusercontent.com/24244919/97084047-8ca96200-1614-11eb-8dd3-fb26e58a7e40.png">

**Comment by PiotrMachowski** [comment]
Thanks, I will try to reproduce and fix it :)

**Comment by darkkatarsis** [comment]
Ok! If I can help somehow, let me know

**Comment by PiotrMachowski** [comment]
I have reproduced, found and fixed a problem. Please download the latest version

**Comment by darkkatarsis** [comment]
> I have reproduced, found and fixed a problem. Please download the latest version

Yes, now all works fine! Thank you for the quick fix

**Comment by PiotrMachowski** [comment]
I'm happy to help :)
