### ISSUE TITLE
Confirmed support for Roborock S4 Max

### ISSUE THREAD

**Issue by JohnnyNoodlez** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#304]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the vacuum/platform is already requested
- [ ] I have sent raw map file to `piotr.machowski.dev [at] gmail.com` ([Retrieving map](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#retrieving-map); please provide your GitHub username in the email)

### What vacuum model do you want to be supported?

roborock.vacuum.a19

### What is its name?

Roborock S4 Max

### Available APIs

- [ ] xiaomi
- [ ] viomi
- [ ] roidmi
- [ ] dreame

### Other info

I use this vacuum with the Lovelace card. I've never had issues thus far. If you would like to request specific tests or info I can do that. I haven't forced the api, but I'm using xaomi cloud on an non-rooted robot.

Just a heads up to add it to the "tested" list on the readme.

**Comment by PiotrMachowski** [comment]
Vacuum added to a list of supported devices. Thanks!
