### ISSUE TITLE
szkj.vacuum.mjfc01

### ISSUE THREAD

**Issue by lasry1** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#309]
### Description

The vacuum szkj.vacuum.mjfc01 is not suported. Not pulling the map.

### Solution

I would like to have the map as with my other (older) vacuum.

**Comment by lasry1** [comment]
How do i get a raw map file?

**Comment by PiotrMachowski** [comment]
Please use a [correct issue template](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/issues/new?assignees=PiotrMachowski&labels=new+platform%2Cenhancement&template=new_platform_request.yml). Everything is described there
