### ISSUE TITLE
Does not import as a camera

### ISSUE THREAD

**Issue by ChillZwix** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#320]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

It will no longer import it as a camera. 

### What version of am integration has described problem?

v2.0.11

### What vacuum model do you have problems with?

Roborock s5

### What version of Home Assistant do you use?

2022.7.3

### What type of installation are you running?

Home Assistant Container

### Camera's configuration

```yaml
platform: xiaomi_cloud_map_extractor
host: !secret xiaomi_vacuum_host
token: !secret xiaomi_vacuum_token
username: !secret xiaomi_cloud_username
password: !secret xiaomi_cloud_password
name: vacuum_map
country: de
draw: ['all']
attributes:
  - calibration_points
```

### Errors shown in the HA logs (if applicable)

```shell
I dont understand the error:

Error while setting up xiaomi_cloud_map_extractor platform for camera
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 250, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 137, in async_setup_platform
    async_add_entities([VacuumCamera(entity_id, host, token, username, password, country, name, should_poll,
  File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 148, in __init__
    self._vacuum = miio.Vacuum(host, token)
AttributeError: module 'miio' has no attribute 'Vacuum'
```

**Comment by PiotrMachowski** [comment]
Was it working before? Are you sure that you have the latest version of the integration installed?

**Comment by PiotrMachowski** [comment]
Try removing and reinstalling it. It really looks like you have an old version

**Comment by ChillZwix** [comment]
A reinstall did the trick.
Thak you for help :)

Case closed!
