### ISSUE TITLE
Path and vacuum is quite pixelated compared to the Xiaomi app itself

### ISSUE THREAD

**Issue by DohmenICT** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#328]
### Description

First of all: Thanks for this! It works great with the Roidmi Eva (wasn't in the supported devices list)

When I view the map with the path and the vacuum, the path and vacuum look quite pixelated compared to what I see in de Xiaomi and Roidmi apps.

This is in HomeAssistant:
![image](https://user-images.githubusercontent.com/7723754/184847569-8a71956b-8686-4234-8cd9-f0a0412421a8.png)

And this is in the app:
![image](https://user-images.githubusercontent.com/7723754/184847099-d1596a1b-6462-4d54-8d35-40e4d455bc14.png)

### Solution

Make the path and the vacuum smoother

### Alternatives

Map and path seem to have the same resolution in this component. Maybe make a setting to increase the resolution of the map so that the details on it can be more detailed.

**Comment by PiotrMachowski** [comment]
This situation is caused by small resolution of a map. You can fix it by increasing `scale`: 
```yaml
map_transformation:
  scale: 2
```
Keep in mind that this will also increase CPU and RAM usage, so you have to find a balance that will suit your needs . Usually `2` should be enough to look ok.

**Comment by DohmenICT** [comment]
Ah great! this is indeed what I was looking for. Thanks Piotr!
