### ISSUE TITLE
Vacuum index / layer position on map

### ISSUE THREAD

**Issue by darkkatarsis** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#34]
It is possible for the vacuum cleaner to appear on a layer above the path but not to cover the zones?

<img width="189" alt="Screenshot 2020-10-27 at 09 28 30" src="https://user-images.githubusercontent.com/24244919/97278751-6c5aec80-183a-11eb-8def-2910d7854d1a.png">

**Comment by PiotrMachowski** [comment]
I think so. I can also try to make draw respect order of values in `draw:` section

**Comment by PiotrMachowski** [comment]
Added in v1.0.2
