### ISSUE TITLE
Mi Robot Vacuum-Mop 2

### ISSUE THREAD

**Issue by dmitriytim** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#346]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the vacuum/platform is already requested
- [X] I have sent raw map file to `piotr.machowski.dev [at] gmail.com` ([Retrieving map](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#retrieving-map); please provide your GitHub username in the email)

### What vacuum model do you want to be supported?

dreame.vacuum.p2140p

### What is its name?

Mi Robot Vacuum-Mop 2

### Available APIs

- [X] xiaomi
- [X] viomi
- [X] roidmi
- [X] dreame

### Errors shown in the HA logs (if applicable)

```shell
Sep 23 13:39:09 *************[1781]: #033[36m2022-09-23 13:39:09.381 DEBUG (SyncWorker_1) [custom_components.xiaomi_cloud_map_extractor.camera] Retrieving map from Xiaomi cloud#033[0m
Sep 23 13:39:09 *************[1781]: #033[36m2022-09-23 13:39:09.523 DEBUG (SyncWorker_1) [custom_components.xiaomi_cloud_map_extractor.dreame.map_data_parser] decoding regular type map#033[0m
Sep 23 13:39:09 *************[1781]: #033[31m2022-09-23 13:39:09.526 ERROR (MainThread) [homeassistant.helpers.entity] Update for camera.xiaomi_cloud_map_extractor fails
Sep 23 13:39:09 *************[1781]: Traceback (most recent call last):
Sep 23 13:39:09 *************[1781]:   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 515, in async_update_ha_state
Sep 23 13:39:09 *************[1781]:     await self.async_device_update()
Sep 23 13:39:09 *************[1781]:   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 710, in async_device_update
Sep 23 13:39:09 *************[1781]:     raise exc
Sep 23 13:39:09 *************[1781]:   File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
Sep 23 13:39:09 *************[1781]:     result = self.fn(*self.args, **self.kwargs)
Sep 23 13:39:09 *************[1781]:   File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 278, in update
Sep 23 13:39:09 *************[1781]:     self._handle_map_data(map_name)
Sep 23 13:39:09 *************[1781]:   File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 335, in _handle_map_data
Sep 23 13:39:09 *************[1781]:     map_data, map_stored = self._device.get_map(map_name, self._colors, self._drawables, self._texts,
Sep 23 13:39:09 *************[1781]:   File "/config/custom_components/xiaomi_cloud_map_extractor/common/vacuum.py", line 36, in get_map
Sep 23 13:39:09 *************[1781]:     map_data = self.decode_map(response, colors, drawables, texts, sizes, image_config)
Sep 23 13:39:09 *************[1781]:   File "/config/custom_components/xiaomi_cloud_map_extractor/dreame/vacuum.py", line 24, in decode_map
Sep 23 13:39:09 *************[1781]:     return MapDataParserDreame.decode_map(raw_map_string, colors, drawables, texts, sizes, image_config)
Sep 23 13:39:09 *************[1781]:   File "/config/custom_components/xiaomi_cloud_map_extractor/dreame/map_data_parser.py", line 51, in decode_map
Sep 23 13:39:09 *************[1781]:     unzipped = zlib.decompress(base64.decodebytes(raw_map_string.encode("utf8")))
Sep 23 13:39:09 *************[1781]: zlib.error: Error -3 while decompressing data: incorrect header check#033[0m
```

### Other info

my config

```
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    force_api: dreame
```

Some time ago (two months) the card appeared, but then disappeared, I tried to delete the card and restart the robot, but it did not help.

**Comment by chadalau** [comment]
Hi, Got the same error Using the same Model

Tried All Apis, same thing

**Comment by EvgeniyShatalov** [comment]
Hello.  I also use this model and also get errors.

**Comment by EvgeniyShatalov** [comment]
Hello. Today, after several reboots of the system and the vacuum cleaner, I received such changes.
Two factor auth required (see logs)

> Logger: homeassistant.components.camera
>Source: helpers/entity_platform.py:797
>Integration: Камера ([documentation](https://www.home-assistant.io/integrations/camera), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+camera%22))
First occurred: 22:13:48 (130 occurrences)
Last logged: 22:24:54
>Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05

>Logger: homeassistant.helpers.entity
Source: helpers/entity.py:527
First occurred: 22:15:09 (4 occurrences)
Last logged: 22:23:59
>Update of camera.xiaomi_cloud_map_extractor is taking over 10 seconds

**Comment by deblynprado** [comment]
Hello everyone!

I'm using this model and I can't get the map too, is there anything else that we can try?

**Comment by deblynprado** [comment]
Just sent you my map @dmitriytim 

![Screen Shot 2023-02-27 at 13 10 52](https://user-images.githubusercontent.com/897135/221617087-650b8cd2-d900-490e-8069-8f38e8d6c798.png)
![Screen Shot 2023-02-27 at 13 11 14](https://user-images.githubusercontent.com/897135/221617106-dd76ea03-091a-4603-89d5-0f2ffd72aa96.png)

**Comment by alzaicko** [comment]
Hi, Got the same error Using the same Model

**Comment by PiotrMachowski** [comment]
Moving the discussion to an issue for all affected vacuums: #459
