### ISSUE TITLE
Reflect auto_update status in camera state

### ISSUE THREAD

**Issue by luisiam** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#363]
### Description

Currently, there is no way to tell if `auto_update` is turned on or not.

### Solution

Is it possible to reflect `auto_update` status in the state of the camera entity? i.e. `idle` when `auto_update` is off and `streaming` when `auto_update` is on.

### Alternatives

Use `input_boolean` and `automation` to keep track of it manually

**Comment by PiotrMachowski** [comment]
Duplicate of #173
