### ISSUE TITLE
Map not updating on Home Assistant

### ISSUE THREAD

**Issue by xtraorange** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#390]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

Last night I connected my Roborock s4 to Home Assistant. I then ran the vacuum, divided the rooms, and reran the vacuum to fix one area (mirror).

For some reason, the map on Home Assistant hasn't been updated. It has about half of the rooms divided and nothing past that point. Oddly, if I load a new "floor" and start vacuuming, it immediately updates what I'm seeing on home assistant according to what the vacuum is seeing.

It's as though a map is stuck on it's old version (even though the app reflects the new one).

I have turned on the logger and get no errors.

Anything I can try?

### What version of an integration has described problem?

v2.2.0

### What vacuum model do you have problems with?

roborock.vacuum.a19

### What version of Home Assistant do you use?

2023.1.4

### What type of installation are you running?

Home Assistant OS

### Camera's configuration

```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ["all"]
    attributes:
      - calibration_points
      - rooms
```

### Errors shown in the HA logs (if applicable)

```shell
None occurred.  The logger seems to be confirming successful extractions:

-01-12 20:16:02.180 DEBUG (SyncWorker_4) [custom_components.xiaomi_cloud_map_extractor.camera] Retrieving map name from device
2023-01-12 20:16:02.481 DEBUG (SyncWorker_4) [custom_components.xiaomi_cloud_map_extractor.camera] Map name roboroommap%2F391211918%2F16
2023-01-12 20:16:02.481 DEBUG (SyncWorker_4) [custom_components.xiaomi_cloud_map_extractor.camera] Retrieving map from Xiaomi cloud
2023-01-12 20:16:02.892 DEBUG (SyncWorker_4) [custom_components.xiaomi_cloud_map_extractor.camera] Map data retrieved
2023-01-12 20:16:02.892 DEBUG (SyncWorker_4) [custom_components.xiaomi_cloud_map_extractor.camera] Map is ok
```

**Comment by xtraorange** [comment]
Also, it correctly draws paths and the vacuum itself as it moves

**Comment by PiotrMachowski** [comment]
Can you show some screenshots? Have you tried restarting the vacuum? (By holding power button for a few seconds)

**Comment by xtraorange** [comment]
I had not tried restarting the device, but I did without success.

Here's what I'm seeing (notice the extra blob on home assistant from the mirror, and the middle rooms undivided):

![Screenshot_20230112-214118_Mi Home](https://user-images.githubusercontent.com/1166896/212232888-59a65b68-0700-4018-a886-7624384dbaa1.jpg)
![Screenshot_20230112-214106_Home Assistant](https://user-images.githubusercontent.com/1166896/212232905-2e395afa-236a-424d-b67f-d0bbfc63f21c.jpg)

**Comment by xtraorange** [comment]
It seems extra odd to me that it's correctly drawing the path and vacuum though

**Comment by PiotrMachowski** [comment]
I think that room is divided, but it just happens to be in the same color. Check out room numbers in attributes of camera entity and add `room_colors` section to your config

**Comment by xtraorange** [comment]
It looks like you're right.  So it is updated, except that it's still showing that right side spill that has been removed from the app map.  Is there a way to hide things like that?

**Comment by PiotrMachowski** [comment]
You probably can change it with color setting: https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#colors-configuration

Probably one from `color_map_wall_v2` or `color_grey_wall`

**Comment by xtraorange** [comment]
That works, thanks!
