### ISSUE TITLE
Add Xiaomi Cloud Map Extractor for Node-red or Windows

### ISSUE THREAD

**Issue by polarrys** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#393]
### Description

Dear Community and Dear Piotr,
I'm using Node-red for my home, and, recently, I buy a Roborock S7. 
I would like to display the map on my node-red supervision like Mi Home app on Android. 

So, I would like if it's possible to create your plug-in (Xiaomi Cloud Map Extractor) for node-red. If not, it is possible to create the plug in for windows. In this case, I would extract my map and send it directly in my nore-red.

Thanks for your help and for your work.

### Solution

Create Xiaomi Cloud Map Extractor for Node-red or Windows

**Comment by PiotrMachowski** [comment]
Node-red is written in JavaScript, creating a plugin would require me to implement it once again in JS and I don't see it happening. You can download a map using [map-processor.py](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/tree/master/scripts#downloading-map-from-xiaomi-cloud), it will work on Windows as well
