### ISSUE TITLE
Support VIOMI SE

### ISSUE THREAD

**Issue by Cigareoc** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#396]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the vacuum/platform is already requested
- [ ] I have sent raw map file to `piotr.machowski.dev [at] gmail.com` ([Retrieving map](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#retrieving-map); please provide your GitHub username in the email)

### What vacuum model do you want to be supported?

viomi.vacuum.v19

### What is its name?

Viomi SE V-RVCLM21A

### Available APIs

- [ ] xiaomi
- [ ] viomi
- [ ] roidmi
- [ ] dreame

### Other info

Good evening! I have this robot for the last 1.5 years Viomi SE V-RVCLM21A,it worked very well until half a year ago through the integrations Viomi Robot Vacuum Cleaner SE with coordinates (V-RVCLM21A-not working for me now) 
Here is coordinates( not working now whith this method)
```
service: vacuum.send_command
data:
command: app_zoned_clean
params:
- - -0.25
- -0.6
- 3.8
- 2.55
- 1
- - -0.25
- -0.6
- 3.8
- 2.55
- 1
```
but now only through with miot auto integration he understands commands like this
Here is by room id
```
service: xiaomi_miot.call_action
data:
entity_id: vacuum.viomi_v19_4b59_robot_cleaner
did: XXXXXXXXXXX
siid: 4
aiid: 13
params:
- 0
- 1
- "14"
```
Here is the link from miot https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:vacuum:0000A006:viomi-v19:1
In your integration I also see the map/rooms,room name and the robot but does not react to commands because when I type on a room i give error """Не удалось вызвать службу xiaomi_miot/call_action. required key not provided @ data['aiid']"""

**Comment by PiotrMachowski** [comment]
Sooo Map Extractor works for you, but you just have a problem with controlling your vacuum using Map Card?

**Comment by PiotrMachowski** [comment]
Ok, so you have a problem with configuration of Map Card. I will close this issue, you can create a discussion [here](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/discussions)
