### ISSUE TITLE
Failed to retrieve device

### ISSUE THREAD

**Issue by Gizmoz69** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#417]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

Hi,

After a total extection of the vacuum cleaner, the card does not load any more. IP adress is OK. Statut, controls work. 

### What version of an integration has described problem?

2.2.0

### What was the last working version of an integration?

2.2.0

### What vacuum model do you have problems with?

Roborock S5 

### What version of Home Assistant do you use?

Home Assistant 2023.3.5 Supervisor 2023.03.1 Operating System 9.5 Interface utilisateur : 20230309.1 - latest

### What type of installation are you running?

Home Assistant Core

### Camera's configuration

```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: 192.168.1.27
    token: 306a4f48644c6f35356a716d6d*****
    username: a*****6@gmail.com	
    password: *******
    name: Roborock_S5
    draw: ['all']
    map_transformation:
      scale: 1
      rotate: 0
      trim:
        top: 0
        bottom: 0
        left: 0
        right: 0
    sizes:
      charger_radius: 1
      vacuum_radius: 1
    attributes:
      - calibration_points
      - charger
      - goto
      - goto_path
      - goto_predicted_path
      - image
      - is_empty
      - map_name
      - no_go_areas
      - no_mopping_areas
      - obstacles
      - path
      - room_numbers
      - rooms
      - vacuum_position
      - vacuum_room
      - walls
      - zones
    auto_update: true
```

### Errors shown in the HA logs (if applicable)

```shell
Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05
18:30:12 – (AVERTISSEMENT) Caméra - message survenu pour la première fois à 18:17:37 et apparu 149 fois.
Got error when receiving: timed out
18:29:53 – (ERREUR) xiaomi_cloud_map_extractor (intégration personnalisée) - message survenu pour la première fois à 18:14:21 et apparu 45 fois.
Update of camera.roborock_s5 is taking over 10 seconds
18:28:36 – (AVERTISSEMENT) helpers/entity.py - message survenu pour la première fois à 18:13:56 et apparu 7 fois.
Failed to retrieve model
18:28:10 – (ERREUR) xiaomi_cloud_map_extractor (intégration personnalisée) - message survenu pour la première fois à 18:14:00 et apparu 5 fois.
Error doing job: Unclosed client session
18:19:41 – (ERREUR) runner.py
Something is blocking Home Assistant from wrapping up the start up phase. We're going to continue anyway. Please report the following info at https://github.com/home-assistant/core/issues: energy, cover.tuya, climate.mqtt, humidifier.mqtt, sensor.inkbird, logger, scene.tuya, http, scene.homeassistant, raspberry_pi, persistent_notification, media_player.samsungtv, system_health, sensor.switchbot, fully_kiosk, radio_browser, map, vacuum, sensor.version, application_credentials, siren.tuya, analytics, logbook, hacs, sensor.hassio, ffmpeg, sun, sensor.template, met, humidifier, scene.mqtt, fan.mqtt, tts, dhcp, counter, switch, light.tuya, weather, hue, switch.tuya, ezviz, humidifier.vesync, usb, mqtt, alarm_control_panel.tuya, text, number, sensor.myEnedis, input_select, bluetooth, blueprint, device_tracker.mobile_app, sensor.hacs, select, media_player.cast, image_upload, trace, twinkly, default_config, binary_sensor.upnp, light.mqtt, zone, stream, zeroconf, vacuum.tuya, button.tuya, input_boolean, sensor.daikin, media_player, conversation, camera.mqtt, bluetooth_adapters, inkbird, tag, system_log, media_source, template, spotify, input_number, sensor.mobile_app, search, climate, api, cover.mqtt, upnp, samsungtv, sensor.command_line, config, alarm_control_panel.mqtt, homeassistant_alerts, binary_sensor.xiaomi_miio, siren, notify, number.tuya, frontend, dlna_dmr, climate.tuya, binary_sensor.ezviz, scene, media_player.spotify, device_tracker.mqtt, number.fully_kiosk, button.fully_kiosk, calendar.google, button.livebox, history, device_tracker.ibeacon, input_text, sensor.energy, binary_sensor.rpi_power, fan, light.vesync, device_tracker, switch.vesync, mobile_app, auth, hassio, input_datetime, media_player.dlna_dmr, binary_sensor.fully_kiosk, person, livebox, fan.tuya, update.hassio, update.mqtt, number.mqtt, binary_sensor.version, camera.ezviz, device_tracker.livebox, ibeacon, calendar, recorder, select.tuya, switch.mqtt, lock.mqtt, switch.daikin, binary_sensor.hassio, onboarding, sensor.tuya, automation, siren.mqtt, sensor.livebox, sensor, lovelace, network, select.mqtt, sensor.xiaomi_miio, timer, schedule, camera.tuya, switch.ezviz, climate.daikin, device_automation, myEnedis, vacuum.xiaomi_miio, tuya, tts.google_translate, my, websocket_api, cloud, weather.met, file_upload, switch.fully_kiosk, lock, binary_sensor.tuya, input_button, hardware, vacuum.mqtt, camera.xiaomi_cloud_map_extractor, daikin, ssdp, google, binary_sensor.mobile_app, sensor.mqtt, humidifier.tuya, cast, button.mqtt, binary_sensor.mqtt, light.twinkly, sensor.ibeacon, xiaomi_miio, switch.livebox, diagnostics, binary_sensor, sensor.ezviz, script, sensor.vesync, sensor.fully_kiosk, repairs, sensor.upnp, button, binary_sensor.livebox, homeassistant, update, cover, webhook, alarm_control_panel, camera, version, notify.mobile_app, binary_sensor.vesync, switchbot, vesync, text.mqtt, rpi_power, number.vesync, light, media_player.fully_kiosk
18:19:36 – (AVERTISSEMENT) core.py
Setup timed out for bootstrap - moving forward
18:19:21 – (AVERTISSEMENT) bootstrap.py
```

**Comment by PiotrMachowski** [comment]
1. Confirm that token and IP address are the same as one in [Tokens Extractor](https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor)
2. Reboot the vacuum by pressing and holding power on button

**Comment by Gizmoz69** [comment]
> 1. Confirm that token and IP address are the same as one in [Tokens Extractor](https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor)
It's the same 
> 2. Reboot the vacuum by pressing and holding power on button
It does not work

log : 
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:541
First occurred: 20:26:53 (8 occurrences)
Last logged: 20:48:04

Update of camera.roborock_s5 is taking over 10 seconds
Update of sensor.salon_inside_temperature is taking over 10 seconds

Logger: homeassistant.components.camera
Source: helpers/entity_platform.py:822
Integration: Caméra (documentation, issues)
First occurred: 20:30:23 (212 occurrences)
Last logged: 20:48:24

Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05

**Comment by Gizmoz69** [comment]
Yes but same log : 

Logger: custom_components.xiaomi_cloud_map_extractor.camera
Source: custom_components/xiaomi_cloud_map_extractor/camera.py:273
Integration: xiaomi_cloud_map_extractor ([documentation](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor), [issues](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/issues))
First occurred: 09:38:29 (1 occurrences)
Last logged: 09:38:29

Got exception while fetching the state: No response from the device

Logger: custom_components.xiaomi_cloud_map_extractor.camera
Source: custom_components/xiaomi_cloud_map_extractor/camera.py:272
Integration: xiaomi_cloud_map_extractor ([documentation](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor), [issues](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/issues))
First occurred: 09:38:09 (2 occurrences)
Last logged: 09:41:43

Failed to retrieve model

Logger: homeassistant.helpers.entity
Source: helpers/entity.py:541
First occurred: 09:38:14 (2 occurrences)
Last logged: 09:41:50

Update of camera.roborock_s5 is taking over 10 seconds

Got error when receiving: timed out

Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05

**Comment by PiotrMachowski** [comment]
It looks like an issue with invalid token

**Comment by Gizmoz69** [comment]
succes ! thanks
