### ISSUE TITLE
Split Map Extractor into a pypi package

### ISSUE THREAD

**Issue by Lash-L** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#418]
### Description

Per our discussion [here](https://github.com/humbertogontijo/python-roborock/pull/9#issuecomment-1483914737), it would be good to have the map extractor as a separate pypi package, so that other integrations/ non-home assistant integrations can use the logic that was created here.

### Solution

Create a separate python repository that holds the logic for map extraction and then host it on pypi.

**Comment by Lash-L** [comment]
Hey @PiotrMachowski let me know how can I help with this. People keep asking me about camera extraction in regards to the core integration, so if you'd like help with Thai I'd be happy to

**Comment by humbertogontijo** [comment]
@PiotrMachowski I'm also glad to help if needed

**Comment by Lash-L** [comment]
Logical to me as well. good for scaling and adding new apis in the future too

**Comment by Lash-L** [comment]
Saw you marked this as in progress, let me know if you need anything!

**Comment by PiotrMachowski** [comment]
@Lash-L I also try to make some refactoring as well. Do you have some suggestions?

**Comment by Lash-L** [comment]
Well this isn't necessarily a suggestion, but the core devs have asked me to try to get Maps directly into HA core as a new Entity. I was wondering if that is something you would be interested in as well? I'm currently working on adding rooms to the Vacuum entity as a kind of first step.


As far as this package goes, I think what you said earlier makes sense about the common package and splitting up code specific stuff. Or even just some basic subclassing. As far as any other specific suggestions go, I don't really have anything.

**Comment by humbertogontijo** [comment]
Making the common package would be nice, but if you want something easier, maybe just creating a CameraEntity receiving some interfaces would also work

**Comment by Lash-L** [comment]
@humbertogontijo how would he make the actual entity in the package since it's not within HA?

**Comment by humbertogontijo** [comment]
@Lash-L not actually implementing the CameraEntity but providing a class to be extended by one implementation

**Comment by PiotrMachowski** [comment]
Quick update: I have finished refactoring and separating code to different packages, now I have to use them in Map Extractor, test everything and publish the results

**Comment by Lash-L** [comment]
Awesome, thanks for the update!

**Comment by PiotrMachowski** [comment]
I have extracted 5 packages:
- [`vacuum-map-parser-base`](https://github.com/PiotrMachowski/Python-package-vacuum-map-parser-base)
- [`vacuum-map-parser-roborock`](https://github.com/PiotrMachowski/Python-package-vacuum-map-parser-roborock)
- [`vacuum-map-parser-viomi`](https://github.com/PiotrMachowski/Python-package-vacuum-map-parser-viomi)
- [`vacuum-map-parser-roidmi`](https://github.com/PiotrMachowski/Python-package-vacuum-map-parser-roidmi)
- [`vacuum-map-parser-dreame`](https://github.com/PiotrMachowski/Python-package-vacuum-map-parser-dreame)

and created an [early version of Map Extractor](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/tree/dev_extracted_libraries) that uses them.

Please feel free to suggest any changes and improvements.

**Comment by Lash-L** [comment]
Perfect! I'll take a stab at implementing it in the custom Roborock component tomorrow and let you know if anything comes up

**Comment by PiotrMachowski** [comment]
@Lash-L Have you found some time to check out created packages?

**Comment by Lash-L** [comment]
Hey @PiotrMachowski I have a local branch adding it for the custom integration, but I still have a bit to do. I've been a bit focused on the core integration, and I can't add it to the core integration until the Floor Plan proposal gets approved.
But I'm thinking this week I'll have a better idea of any pain points with integrating the packages. Sorry for the delay!

**Comment by PiotrMachowski** [comment]
I have seen your Floor Plan proposal, it seems to be a quite big architectural change for HA. Anyway, I'm not pushing you, I'm just curious if my solution fits your needs.

**Comment by Lash-L** [comment]
> I have seen your Floor Plan proposal, it seems to be a quite big architectural change for HA

Definitely is - still optimistic I'll be able to get something done as Paulus seems interested in the concept.

But for now I am just adding it as an image to the core entity. But question for you - it is working well, but it seems like the roborock extractor does not set the names of the rooms. And the image parser doesn't have the draw_room_name function like the generic one does. 

Am I missing something?

**Comment by PiotrMachowski** [comment]
Are room names included in rrmap file?

**Comment by Lash-L** [comment]
Not that I am aware of - but they can be gotten through another command. Perhaps just being able to pass in a dictionary to map from room ids to names? Or would it be better if I just manually draw the text afterwards? I'm not sure, still working my way around this package

**Comment by PiotrMachowski** [comment]
I thiiink you can pass them using texts parameter. But to be honest I don't really like drawing texts on the map - by default it uses a non-scalable bitmap font that doesn't support any special characters and I don't think HA contains other fonts that are available for pillow to use.
