### ISSUE TITLE
install to HassOS 4.16

### ISSUE THREAD

**Issue by Pavel-Efimov** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#42]
When im tryin to add repo i got this error
`20-11-13 13:33:00 ERROR (MainThread) [supervisor.utils.json] Can't read json from /data/addons/git/7fee8d21/repository.json: [Errno 2] No such file or directory: '/data/addons/git/7fee8d21/repository.json'
20-11-13 13:33:00 ERROR (MainThread) [supervisor.store] https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor is not a valid add-on repository. `

**Comment by cathelest** [comment]
Add to HACS, not supervisor,

**Comment by PiotrMachowski** [comment]
Exactly, it's a custom component, not add-on.
