### ISSUE TITLE
Restricted Areas, Dock, Vacuum and Path are all offset to the right

### ISSUE THREAD

**Issue by akshay7394** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#430]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the vacuum/platform is already requested
- [x] I have sent raw map file to `piotr.machowski.dev [at] gmail.com` ([Retrieving map](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#retrieving-map); please provide your GitHub username in the email)

### What vacuum model do you want to be supported?

viomi.vacuum.v10

### What is its name?

Xiaomi Mi Vacuum Mop P

### Available APIs

- [x] xiaomi
- [X] viomi
- [ ] roidmi
- [ ] dreame

### Other info

I just need to offset either the map towards the right side (further along the x-axis), or I need to offset the dock+vacuum+path to the left on the x-axis

I can't seem to find any kind of offset option and looking through the past issues and the readme hasn't helped (maybe it's there and I'm not understanding it)

Would someone be able to help whenever possible?

**Comment by akshay7394** [comment]
![image](https://user-images.githubusercontent.com/934532/234365596-a0b6cc42-4049-41f6-afed-a3d2fb53a124.png)

Here is a picture of the map. The vacuum is shown in the entry way (green room on the map, in the centre) whereas it is actually in one of the living areas (light blue room on the map, bottom-left)

**Comment by PiotrMachowski** [comment]
It looks like the same issue as here:
https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/issues/189

Can you send me your raw map?

**Comment by akshay7394** [comment]
Is the raw map the z-lib file? If so, here you go.

> It looks like the same issue as here:
> #189
> <https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/issues/189>
>
> Can you send me your raw map?
>

**Comment by PiotrMachowski** [comment]
Yes, this is the file, thanks

**Comment by akshay7394** [comment]
No problem. Let me know if there's anything I could change that'd fix this!
If not, I'll just exclude all drawings except rooms; it's not a huge deal :)

**Comment by PiotrMachowski** [comment]
@akshay7394 you can try to delete the map in Xiaomi Home, it might help

**Comment by akshay7394** [comment]
But I only have 1 map, would have to re-map my entire house again 😅 I think I'll just live with it and turn off the drawings, but thank you for checking!
