### ISSUE TITLE
Current position/room sensor.

### ISSUE THREAD

**Issue by maxi1134** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#435]
### Description

I think that a way to know in which room the robot currently is could be very useful for automations.

### Solution

A sensor that provides the current location of the vacuum in terms of room or X/Y positions.

### Alternatives

I thought about tracking the robot with a BLE beacon, but that seems like a lot of trouble when we already have the map with the coordinates in this component.

**Comment by PiotrMachowski** [comment]
It is already possible:
```yaml
attributes:
  - vacuum_room
  - vacuum_position
```

**Comment by maxi1134** [comment]
Thanks!

**Comment by PiotrMachowski** [comment]
Are numbers in Mi Home consecutive?
