### ISSUE TITLE
Add "sleeping" as a state for the camera updates to stop

### ISSUE THREAD

**Issue by brhahlen** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#437]
### Description

I'm using the recommended blueprint (https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/blob/master/blueprints/automation/update_map_extractor.yaml) to stop the updates of the camera, to ensure that I not get rate limited.

However, when my vacuum gets stuck somewhere, it will go into a "sleeping" state, which will still cause regular updates, and casuse me to be rate limited.

### Solution

Add a "sleeping" state to the `Update Map Extractor` blueprint, that will stop updates when the vacuum goes into a sleeping state.

**Comment by PiotrMachowski** [comment]
Good idea, done!

**Comment by brhahlen** [comment]
Holy crap, that was fast!
Thanks!
