### ISSUE TITLE
Please add support for Roborock S8

### ISSUE THREAD

**Issue by multinet33** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#452]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the vacuum/platform is already requested
- [X] I have sent raw map file to `piotr.machowski.dev [at] gmail.com` ([Retrieving map](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#retrieving-map); please provide your GitHub username in the email)

### What vacuum model do you want to be supported?

roborock.vacuum.a51

### What is its name?

Roborock S8

### Available APIs

- [ ] xiaomi
- [ ] viomi
- [ ] roidmi
- [ ] dreame

### Other info

Hello Piotr he would be great if you add support for S8 Roborock

**Comment by PiotrMachowski** [comment]
It should work right now, have you tried it?

**Comment by multinet33** [comment]
Hum still not working ("failed to retrieve..") BUT 'm using Roborock app and not xiaomi app

Maybe is it the root cause ?

**Comment by PiotrMachowski** [comment]
Map Extractor doesn't work with Roborock app, you have to use [this integration](https://github.com/humbertogontijo/homeassistant-roborock) instead
