### ISSUE TITLE
The Generic IP Camera YAML configuration is being removed

### ISSUE THREAD

**Issue by dabepp** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#456]
### Description

This stops working in version 2024.2.0. Please address before upgrading.
Configuring Generic IP Camera using YAML is being removed.

Your existing YAML configuration has been imported into the UI automatically.

Remove the generic configuration from your configuration.yaml file and restart Home Assistant to fix this issue.

### Solution

Is there a way to include this in the UI?

### Context

I have updated HASS to 2023.8.0 and  the Cloud Map Extractor is setup via YAML as generic Camera. I removed the YAML configuration and then the map is not shown any more...

**Comment by PiotrMachowski** [comment]
This log message is not related to map extractor

**Comment by dabepp** [comment]
It is, the map extractor uses the generic camera yaml integration which will be deprecated in 2024.1
So when I remove the YAML configuration for the map extractor the map is not working anymore. Or is there another way to show the map?

**Comment by PiotrMachowski** [comment]
[This](https://www.home-assistant.io/integrations/generic/) is generic camera integration, which is not related to Map Extractor
