### ISSUE TITLE
No entity appear after reboot and modify config.yaml

### ISSUE THREAD

**Issue by dimed89** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#481]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

Hello, After installation of xiaomi cloud map I follow the instructions for modify the config.yaml I add this :
<img width="374" alt="image" src="https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/assets/122288146/cda20c62-0af7-4612-b1e1-574f277b4c1e">

And after I reboot my systeme the enity will be not appear I really don't understand why its not working can you help me please? I'm noob ^^

### What version of an integration has described problem?

v.2.2.1

### What was the last working version of an integration?

v.2.2.1

### What vacuum model do you have problems with?

vaccum s50

### What version of Home Assistant do you use?

2023.10.3

### What type of installation are you running?

Home Assistant OS

### Camera's configuration

```yaml
what configuration?
```

**Comment by PiotrMachowski** [comment]
Have you defined all secrets? Have you checked HA logs?

**Comment by dimed89** [comment]
Hey, yes and nothing after this I totaly delete the integration re install complete and its working for 3 hour but now, my map on my xiaomi map was delete, I reset my roborock re include with xiaomi milo on HA the vaccum working and on xiaomi map cloud I didnt see my map and also in my xiaomi app after reset the vaccum

**Comment by PiotrMachowski** [comment]
Soooo it's working now?

**Comment by dimed89** [comment]
it worked for a few hours and after that the map of my house no longer loads on the mi home application, I get a message that tells me "loading the map" but it loads endlessly. I hard reset the robot your integration on my home assistant, change account, change the IP of the robot same thing the card loads infinitely since the installation of the integration yesterday

**Comment by PiotrMachowski** [comment]
Ok, so this is a different problem now: https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/issues/422
