### ISSUE TITLE
unavailable h

### ISSUE THREAD

**Issue by kaelsaes** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#483]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

Although the map is showing correct, "unavailable h" is shown at the Sensors left, Filter left, Main brush left, Side brush left.

### What version of an integration has described problem?

V2.2.2

### What was the last working version of an integration?

?

### What vacuum model do you have problems with?

Vacuum 1

### What version of Home Assistant do you use?

2023.10.5

### What type of installation are you running?

Home Assistant Supervised

### Camera's configuration

```yaml
Recommended installation
```

**Comment by PiotrMachowski** [comment]
This is not related to Map Extractor. Data shown on the Map Card comes form the integration you use to control vacuum in HA
