### ISSUE TITLE
Doesn't show map in HA and MiApp

### ISSUE THREAD

**Issue by Bkk20** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#484]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

Since I integrated MapExtractor in HA after few days the map was gone and also in the MiApp. I everything to get the map back in the MiApp but not successful. 
Any idea? 
Honestly,  it should be recognized before integrating MapExtractor.
Someone know what I should so?

### What version of an integration has described problem?

2.2.1

### What vacuum model do you have problems with?

MI robot 

### What version of Home Assistant do you use?

2023.10.5

### What type of installation are you running?

Home Assistant Container

### Camera's configuration

```yaml
No
```

**Comment by PiotrMachowski** [comment]
#422
