### ISSUE TITLE
v-rvclm26b viomi.vacuum.v6

### ISSUE THREAD

**Issue by Grifindorec** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#497]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the vacuum/platform is already requested
- [ ] I have sent raw map file to `piotr.machowski.dev [at] gmail.com` ([Retrieving map](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#retrieving-map); please provide your GitHub username in the email)

### What vacuum model do you want to be supported?

viomi.vacuum.v6

### What is its name?

v-rvclm26b

### Available APIs

- [ ] xiaomi
- [ ] viomi
- [ ] roidmi
- [ ] dreame

### Errors shown in the HA logs (if applicable)

```shell
Эта ошибка возникла в пользовательской интеграции.

Logger: custom_components.xiaomi_cloud_map_extractor.camera
Source: custom_components/xiaomi_cloud_map_extractor/camera.py:309
Integration: xiaomi_cloud_map_extractor (documentation, issues)
First occurred: 20:21:29 (1 occurrences)
Last logged: 20:21:29

Failed to retrieve model

Эта ошибка возникла в пользовательской интеграции.

Logger: miio.device
Source: custom_components/xiaomi_cloud_map_extractor/camera.py:320
Integration: xiaomi_cloud_map_extractor (documentation, issues)
First occurred: 20:21:35 (1 occurrences)
Last logged: 20:21:35

Found an unsupported model 'viomi.vacuum.v6' for class 'RoborockVacuum'. If this is working for you, please open an issue at https://github.com/rytilahti/python-miio/
```

**Comment by PiotrMachowski** [comment]
`viomi.vacuum.v6` should work with this integration. What is your config?

**Comment by Grifindorec** [comment]
sorry for long reply.
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ["all"]
    attributes:
      - calibration_points
    auto_update: false

**Comment by PiotrMachowski** [comment]
What does the camera show? Is there anything more in logs?

**Comment by Grifindorec** [comment]
still don't work( without auto_update: false - Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05
tried interval 30 sec, don't work.
camera show "failed to retrieve device"
![image](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/assets/140441057/cde8c1c3-03d3-440e-8053-2be69faaafa4)

**Comment by PiotrMachowski** [comment]
This means the token you have provided doesn't match any device

**Comment by Grifindorec** [comment]
hello
i have alredy devices in other platform - majordmo. and token in this platform and in mi home from vevs are the same.

![image](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/assets/140441057/04219b2f-bc9a-4b04-a019-28fb98dcf774)
![image](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/assets/140441057/1feed2d6-4832-4f60-af4a-37e2e0d3d7fe)

**Comment by PiotrMachowski** [comment]
Can you check if [Tokens Extractor](https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor) returns the same token?

**Comment by Grifindorec** [comment]
sure
![image](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/assets/140441057/8bd33661-26d6-4509-9afb-32ef62153012)

**Comment by Grifindorec** [comment]
Hello
Any idea?

**Comment by Grifindorec** [comment]
Sorry, it's my fault.
So stupied mistake in configuration.yaml
Please add that v-rvclm26b work too
Coffee on me

**Comment by PiotrMachowski** [comment]
I'm glad you have figured it out 👍
