### ISSUE TITLE
Websocket command 'camera_thumbnail' has been deprecated

### ISSUE THREAD

**Issue by iophobia** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#56]
Hi,
not necessarily a bug report but a heads-up that the websocket command 'camera_thumbnail' has been deprecated w/ HA Core 2020.12.0
Hence no map is shown.

**Comment by PiotrMachowski** [comment]
It's not a problem with this component, but with a [map card](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/issues/67)
