### ISSUE TITLE
Rooms looks "greyed out" compared to the app

### ISSUE THREAD

**Issue by Maximus97** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#59]
I do not know why, but the color of my rooms look greyed out compared to the app. Is this some setting? It looks like my whole map is covered by the "grey" color that is shown in this figure. (This image is taken from you in this repository)
![image](https://user-images.githubusercontent.com/42326685/102702710-e4a3c400-4265-11eb-8ad9-4748b597f074.png)

**Comment by PiotrMachowski** [comment]
Yes, all colors are configurable [documentation](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#colors-configuration)

**Comment by Maximus97** [comment]
How do I make that color transparent? Which color name is it?

**Comment by PiotrMachowski** [comment]
It's probably `color_grey_wall`
