### ISSUE TITLE
Testing Config Changes

### ISSUE THREAD

**Issue by krystiancharubin** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#6]
Is there a way to test config changes without having to restart HA every time?

**Comment by PiotrMachowski** [comment]
Right now it's not possible. Maybe I will try to implement config flow, in this case you will be able to completely configure this integration via UI.

**Comment by krystiancharubin** [comment]
Would it be easy to run the python code from terminal to spit out an image?

**Comment by PiotrMachowski** [comment]
That's doable, I plan to prepare some scripts soon

**Comment by PiotrMachowski** [comment]
I added scripts [here](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/tree/master/scripts).

Before running you have to configure them (code between `CONFIGURATION` and `CONFIGURATION END`).

Python files of a component must be in the same direction as ones from scripts.

To open binary map data you can use [RoboMapViever](https://github.com/marcelrv/XiaomiRobotVacuumProtocol/tree/master/RRMapFile).

These scripts are not tested yet, so there may some issues. I will include them in a documentation later.

**Comment by leva3000** [comment]
@krystiancharubin I suggest the really great portable version of HA https://github.com/AlexxIT/HassWP.
It's just an 82M archive. You can set up your configuration and quickly restart the portable instance using the preadded script button on lovelace. I spent like 5-10 minutes to adjust settings.

**Comment by PiotrMachowski** [comment]
@leva3000 WOW! I didn't know about this tool!

**Comment by PiotrMachowski** [comment]
@leva3000 I have made a script for getting tokens of Xiaomi devices, you can check it out [here](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/blob/master/scripts/) 🙂

**Comment by leva3000** [comment]
Almost everybody in the Russian HA community is used modified Mi Home apk before solutions like yours and Alex's were implemented. Thank you!

**Comment by PiotrMachowski** [comment]
Added possibility to reload config from yaml file in v2.0.3
