### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by lipwah** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#60]
Platform error camera.xiaomi_cloud_map_extractor - Requirements for xiaomi_cloud_map_extractor not found: ['python-secrets'].

**Comment by PiotrMachowski** [comment]
HA restart should solve the problem

**Comment by lipwah** [comment]
> HA restart should solve the problem

Supervisor
Version
2020.12.7

camera:
  - platform: xiaomi_cloud_map_extractor
    host: 192.168.3.xxx
    token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    username: xxxxxxx
    password: xxxxxxxxxxxxxxx
    draw: ["all"]
    colors:
      color_map_inside: [32, 115, 185]
      color_map_outside: [19, 87, 148]
      color_map_wall: [100, 196, 254]
      color_grey_wall: [93, 109, 126]
      color_path: [147, 194, 238]
      color_virtual_walls: [255, 0, 0]
      color_charger: [0x66, 0xfe, 0xda, 0x7f]
      color_robo: [75, 235, 149]
      color_unknown: [0, 0, 0]
    attributes:
      - calibration_points

Unable to install package python-secrets: ERROR: Exception: Traceback (most recent call last): File "/usr/local/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 437, in _error_catcher yield File "/usr/local/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 519, in read data = self._fp.read(amt) if not fp_closed else b"" File "/usr/local/lib/python3.8/http/client.py", line 458, in read n = self.readinto(b) File "/usr/local/lib/python3.8/http/client.py", line 502, in readinto n = self.fp.readinto(b) File "/usr/local/lib/python3.8/socket.py", line 669, in readinto return self._sock.recv_into(b) File "/usr/local/lib/python3.8/ssl.py", line 1241, in recv_into return self.read(nbytes, buffer) File "/usr/local/lib/python3.8/ssl.py", line 1099, in read return self._sslobj.read(len, buffer) socket.timeout: The read operation timed out During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/local/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 228, in _main status = self.run(options, args) File "/usr/local/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper return func(self, options, args) File "/usr/local/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 323, in run requirement_set = resolver.resolve( File "/usr/local/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 183, in resolve discovered_reqs.extend(self._resolve_one(requirement_set, req)) File "/usr/local/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 388, in _resolve_one abstract_dist = self._get_abstract_dist_for(req_to_install) File "/usr/local/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 340, in _get_abstract_dist_for abstract_dist = self.preparer.prepare_linked_requirement(req) File "/usr/local/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 467, in prepare_linked_requirement local_file = unpack_url( File "/usr/local/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 255, in unpack_url file = get_http_url( File "/usr/local/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 129, in get_http_url from_path, content_type = _download_http_url( File "/usr/local/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 282, in _download_http_url for chunk in download.chunks: File "/usr/local/lib/python3.8/site-packages/pip/_internal/network/utils.py", line 64, in response_chunks for chunk in response.raw.stream( File "/usr/local/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 576, in stream data = self.read(amt=amt, decode_content=decode_content) File "/usr/local/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 541, in read raise IncompleteRead(self._fp_bytes_read, self.length_remaining) File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__ self.gen.throw(type, value, traceback) File "/usr/local/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 442, in _error_catcher raise ReadTimeoutError(self._pool, None, "Read timed out.") pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.

**Comment by PiotrMachowski** [comment]
It seems to be a problem on a HA side

**Comment by LLIYTHUK** [comment]
i fix this error when delete "python-secrets", from manifest.json
if you used python3.6 or later secrets native build in.
