### ISSUE TITLE
Missing from HACS

### ISSUE THREAD

**Issue by TeoTN** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#64]
The extractor is gone from Hacs list, it's neither in the repositories browser in app nor on the hacs.xyz page. Could you please restore it to simplify the integration process?

**Comment by PiotrMachowski** [comment]
It was never available in HACS by default, it has to be added as a custom repository

**Comment by TeoTN** [comment]
Ah, I see, I misunderstood the readme docs - being new to hacs I didn't know you can add a custom repo using it rather than cloning it manually :) Thanks!

**Comment by PiotrMachowski** [comment]
I forgot to close this issue, this integration is available in HACS by default now

**Comment by tomlut** [comment]
Nope. Still not in HACS:

![Screenshot 2022-06-25 at 13-14-54 HACS – Home Assistant](https://user-images.githubusercontent.com/10679300/175756103-7479a7ce-b0df-43bc-838d-4f9a08468351.png)
