### ISSUE TITLE
HA rebooting

### ISSUE THREAD

**Issue by loop2** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#65]
Hi! I've installed the cloud map extractor as described and I also installed xiaomi_miio in order to set commands to the vacuum... but when I reboot HA with the cloud map extractor compute in the configuration file... HA reboot every 1-2 minutes...

**Comment by PiotrMachowski** [comment]
Can you provide some additional info?
* What hardware do you have?
* What type of installation do you have?
* Do you see any change in CPU/RAM usage?

**Comment by loop2** [comment]
Yes!
HA running on VMware machine with 2 Core and 4GB of RAM.
After the activation of this component the ram used raising until the server reboots. On the virtual machine I receive a message: Out of memory: Killed process (python3)

**Comment by PiotrMachowski** [comment]
Does a map appear?

**Comment by loop2** [comment]
I also tried with 4 core CPU and 8GB of RAM... same issue
Yes I can see the map with this config:
`camera:
  - platform: xiaomi_cloud_map_extractor
    host: 10.0.2.16
    token: 5961703850374876466f646c49336632
    username: alessandrodl@hotmail.com
    password: 09ale980
    colors:
      color_map_inside: [32, 115, 185]
      color_map_outside: [0, 0, 0, 0]
      color_map_wall: [100, 196, 254]
      color_map_wall_v2: [93, 109, 126]
      color_grey_wall: [93, 109, 126]
      color_path: [0, 0, 0]
      color_goto_path: [0, 255, 0]
      color_predicted_path: [255, 255, 0, 0]
      color_zones: [0xAD, 0xD8, 0xFF, 0x8F]
      color_zones_outline: [0xAD, 0xD8, 0xFF]
      color_virtual_walls: [255, 0, 0]
      color_no_go_zones: [255, 33, 55, 127]
      color_no_go_zones_outline: [255, 0, 0]
      color_no_mop_zones: [163, 130, 211, 127]
      color_no_mop_zones_outline: [163, 130, 211]
      color_charger: [0x66, 0xfe, 0xda, 0x7f]
      color_robo: [75, 235, 149]
      color_unknown: [0, 0, 0]
      color_scan: [0xDF, 0xDF, 0xDF]
    scan_interval:
      seconds: 10
    auto_update: true
    attributes:
      - calibration_points
      - charger
      - goto
      - goto_path
      - goto_predicted_path
      - image
      - is_empty
      - map_name
      - no_go_areas
      - no_mopping_areas
      - obstacles
      - path
      - room_numbers
      - rooms
      - vacuum_position
      - vacuum_room
      - walls
      - zones
    draw:
      - charger
      - path
      - goto_path
      - predicted_path
      - no_go_zones
      - no_mopping_zones
      - vacuum_position
      - virtual_walls
    map_transformation:
      scale: 45
      rotate: 180
      trim:
        top: 20
        bottom: 20
        left: 20
        right: 20
    sizes:
      charger_radius: 50
      vacuum_radius: 50`

**Comment by PiotrMachowski** [comment]
Please add again, your secret data was still visible in the history

**Comment by loop2** [comment]
Sorry...
``
camera:
  - platform: xiaomi_cloud_map_extractor
    host: 10.0.2.16
    token: XXXX
    username: XXXX
    password: XXXX
    colors:
      color_map_inside: [32, 115, 185]
      color_map_outside: [0, 0, 0, 0]
      color_map_wall: [100, 196, 254]
      color_map_wall_v2: [93, 109, 126]
      color_grey_wall: [93, 109, 126]
      color_path: [0, 0, 0]
      color_goto_path: [0, 255, 0]
      color_predicted_path: [255, 255, 0, 0]
      color_zones: [0xAD, 0xD8, 0xFF, 0x8F]
      color_zones_outline: [0xAD, 0xD8, 0xFF]
      color_virtual_walls: [255, 0, 0]
      color_no_go_zones: [255, 33, 55, 127]
      color_no_go_zones_outline: [255, 0, 0]
      color_no_mop_zones: [163, 130, 211, 127]
      color_no_mop_zones_outline: [163, 130, 211]
      color_charger: [0x66, 0xfe, 0xda, 0x7f]
      color_robo: [75, 235, 149]
      color_unknown: [0, 0, 0]
      color_scan: [0xDF, 0xDF, 0xDF]
    scan_interval:
      seconds: 10
    auto_update: true
    attributes:
      - calibration_points
      - charger
      - goto
      - goto_path
      - goto_predicted_path
      - image
      - is_empty
      - map_name
      - no_go_areas
      - no_mopping_areas
      - obstacles
      - path
      - room_numbers
      - rooms
      - vacuum_position
      - vacuum_room
      - walls
      - zones
    draw:
      - charger
      - path
      - goto_path
      - predicted_path
      - no_go_zones
      - no_mopping_zones
      - vacuum_position
      - virtual_walls
    map_transformation:
      scale: 45
      rotate: 180
      trim:
        top: 20
        bottom: 20
        left: 20
        right: 20
    sizes:
      charger_radius: 50
      vacuum_radius: 50

**Comment by PiotrMachowski** [comment]
Ok, I think I see the problem... Do you really need `scale: 45`?

**Comment by loop2** [comment]
Maybe also bigger... I wold see the map about half screen on the tablet... I'm using this configuration for the vacuum:
[https://github.com/lukevink/hass-config-lajv](https://github.com/lukevink/hass-config-lajv)

As you can see in the page on the second image there is a clean up page with the map of the floor... i'm using the exported map instead of the floor map..
There is another way like a zoom in order to zoom in the map?

**Comment by PiotrMachowski** [comment]
What resolution do you need?

**Comment by loop2** [comment]
about 800x600px

**Comment by PiotrMachowski** [comment]
In this case `scale: 2` should be enough

**Comment by loop2** [comment]
OK, i have used `scale: 2` and zoom un the ui! now the ram is lower e the map bigger! Thanks a lot!
