### ISSUE TITLE
bigger map

### ISSUE THREAD

**Issue by rhgiter** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#69]
is it possible to make the map bigger ?
![image](https://user-images.githubusercontent.com/61065752/104480802-4507f600-55c5-11eb-950b-6507d5e41093.png)

**Comment by PiotrMachowski** [comment]
Yes, you can trim unnecessary margins: [documentation](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#map-transformation-configuration)
