### ISSUE TITLE
Add "fr" country

### ISSUE THREAD

**Issue by Quintus-s** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#7]
"Tout est dans le titre", as we say  in France.

If it is possible to add this country, this component would be fantastic.

Thanks in advance.

**Comment by PiotrMachowski** [comment]
Are you sure that you shouldn't be using "de"? This is a country of a server, not of a user ;)

**Comment by Quintus-s** [comment]
I'm currently connected on France server. But I know my devices can work on deutch server.

If it's too difficult for you, I can switch to deutch! 

Thanks

**Comment by PiotrMachowski** [comment]
I didn't know that there is a `fr` server. That's not a problem at all, I will add it.

**Comment by Quintus-s** [comment]
You rock! 👍

**Comment by PiotrMachowski** [comment]
I have checked and there is no "fr" server, so I won't add a new country.

**Comment by Quintus-s** [comment]
Oh? Okay...weird, because I'm on it.

Once again, it's not a problem, I will change to the deutch server. Same for me.

Thank you

**Comment by PiotrMachowski** [comment]
Maybe it has completely different address that I am not aware about. I will look for any news in this topic
