### ISSUE TITLE
HA not restarting after reboot - custom integration?

### ISSUE THREAD

**Issue by edgardavim** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#73]
Hello,

a bit new on this topic, I was trying to follow the steps to install the map. After reboot the HA did not came back. Created now a new yaml for lovelace which reduced the warnings. Now still have as per below and don't know what else to actually fix it.

WARNING (MainThread) [homeassistant.setup] Setup of person is taking over 10 seconds.
WARNING (MainThread) [homeassistant.loader] You are using a custom integration for xiaomi_cloud_map_extractor which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.

Any idea where the custom integration can be affecting?

**Comment by PiotrMachowski** [comment]
This warning is always displayed for all custom components, you can ignore it
