### ISSUE TITLE
Repository is not valid add-on

### ISSUE THREAD

**Issue by vfedosieiev** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#74]
Can't add cloud-map-extractor in HA via custom repo.

`21-01-25 19:58:11 ERROR (MainThread) [supervisor.store] https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor is not a valid add-on repository
21-01-25 19:58:11 ERROR (MainThread) [supervisor.utils.json] Can't read json from /data/addons/git/7fee8d21/repository.json: [Errno 2] No such file or directory: '/data/addons/git/7fee8d21/repository.json'`

**Comment by PiotrMachowski** [comment]
This is not an add-on, it is a custom component. You have to add it to HACS
