### ISSUE TITLE
Integration doesn't work so seeking for some help about debugging

### ISSUE THREAD

**Issue by Snakesms** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#79]
Hi Piotr,

Thanks for another great custom integration.
Unfortunately, I can't manage to let it work.
I did try with recommended & basic configuration options with the same result.

In the main HA log there are warnings about the delay in response:
"Update of camera.xiaomi_cloud_map_extractor is taking over 10 seconds"
And on the camera itself, there is no image.
In the state section I can see:

```
access_token: d96da261e5d483b06a857daeb28aff373bce38xxxxxxxxxxxxxxxxxxxx
friendly_name: Xiaomi Cloud Map Extractor
entity_picture: /api/camera_proxy/camera.xiaomi_cloud_map_extractor?token=d96da261e5d483b06a857daeb28aff373bce38xxxxxxxxxxxxxxxxxxxx
supported_features: 0
```

The Vacuum being called in the app: "rockrobo.vacuum.v1" which I suppose is the same as
(Xiaomi Vacuum Gen 1 (Mi Robot Vacuum/SDJQR01RR/SDJQR02RR)) however not 100% confident about the same

Please kindly advise how I can continue an investigation to nail down the rootcause of the issue
Regards, Sergiy

**Comment by PiotrMachowski** [comment]
Hi,

Please check if vacuum is available in your network and if credentials and token are correct. You can do it using [tokens extractor](https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor)

**Comment by Snakesms** [comment]
Sure, this is what I did by default.
I do use modified Xiaomi Mi Home app where I did double check that the token is correct and Vacuum is visible/accessible by Mi Home and HA

**Comment by PiotrMachowski** [comment]
Maybe requests are being blocked? Do you use adguard or something similar?

**Comment by Snakesms** [comment]
Piotr, Thats interesting point.
I do have Pi-Hole in place.
Let me try to disable it for some time and see if it makes any difference.
If you don't mind to clarify in few words what is the workflow for the camera update between Vauum, HA server and some thirdparties that involved?

Thanks, Sergiy

**Comment by PiotrMachowski** [comment]
Map update sequence works this way:
* HA: Log in to Xiaomi cloud (if necessary)
* HA: Send request for a map name to a vacuum
* Vacuum: Upload map to Xiaomi cloud
* Vacuum: Return map name to HA
* HA: Get map URL from Xiaomi Cloud
* HA: Download map from Xiaomi Cloud

**Comment by Snakesms** [comment]
Thanks for the info Piotr,
It looks like Pi-Hole cause  problems for me, after switching it off I can see the map.
Just one more thing to clarify, is it expected that I don't see the vacuum's track ( just a map of the floor) in HA?
Or I need to tune something with colours?
Thanks

**Comment by Snakesms** [comment]
No worries, sorted by switching from basic config to the recommended one

**Comment by Snakesms** [comment]
The problem came from blocking traffic between the Xiaomi server and HA, you have to keep in mind that the map is downloaded from the internet and not directly from a vacuum.
