### ISSUE TITLE
Transparency

### ISSUE THREAD

**Issue by krystiancharubin** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#8]
```
colors:
      color_map_outside: [0, 0, 0, 0]
```

Transparent color gets rendered as black by the camera entity.
Also using this in a custom card with camera_thumbnail websocket call returns a jpeg.
Possible that HA is treating everything as jpeg behind the scenes thus breaking transparency.

![download](https://user-images.githubusercontent.com/17775600/95399890-41cee100-08d7-11eb-8ddc-681aacac7fda.jpg)

**Comment by PiotrMachowski** [comment]
I am not sure if transparency is supported by HA cameras, I will check it out.

**Comment by PiotrMachowski** [comment]
Done in #21
