### ISSUE TITLE
SCAN_INTERVAL is hard-coded to 5 ?

### ISSUE THREAD

**Issue by licheng5625** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#80]
SCAN_INTERVAL = timedelta(seconds=5)
I did not see any setter after, it is set by the home assistant core ?

thank you 

regards
Cheng

**Comment by PiotrMachowski** [comment]
It is retrieved on higher level, 5 is a default value. It can be overriden, as explained in documentation
