### ISSUE TITLE
Map not loading

### ISSUE THREAD

**Issue by Jese44** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#82]
Hi, so a while ago i was able to install the map and it worked flawlessly, but then randomly it's not loading/showing the map anymore, i have no clue why this began to happen, all "big things" i've done was updating HA firmware, nothing else i can think of. Once after this problem occured the map did load and show correctly, but after that not once. i have no clue, how could i troubleshoot this.

**Comment by Jese44** [comment]
Now after i updated HA core and OS suddenly the image preview worked and the map showed up in the card.... i'll report if it goes missing again, but i have no clue what broke it and why and what possibly fixed it......

**Comment by PiotrMachowski** [comment]
Please check for anything in logs

**Comment by Jese44** [comment]
> Please check for anything in logs

Which log info you'd like me to see? at least "logbook" had nothing regarding to "camera.vacuumname"

**Comment by PiotrMachowski** [comment]
HA logs are available using UI: `<HA_URL>/config/logs` or in `home-assistant.log` file. Right now it will probably be empty, you can check it when this problem will occur again

**Comment by jonydebu** [comment]
Hi , same here stop working .

**Comment by minkola** [comment]
Hello
thank you for making this integration but it has stopped working for me too

22/02/2021

Update of camera.xiaomi_cloud_map_extractor is taking over 10 seconds
13:45:21 – helpers/entity.py (WARNING) - message first occurred at 13:42:31 and shows up 11 times
Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05
13:45:21 – Camera (WARNING) - message first occurred at 13:43:41 and shows up 20 times
Got exception while fetching the state: Unable to discover the device 192.168.1.105
13:42:46 – xiaomi_cloud_map_extractor (WARNING)
Setup of vacuum platform xiaomi_miio is taking over 10 seconds.
13:42:31 – Vacuum (WARNING)

You are using a custom integration for xiaomi_cloud_map_extractor which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
13:42:15 – loader.py (WARNING)

**Comment by 8osman** [comment]
Thanks for the integration, I have the same problem, home assistant in docker. 

`  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 474, in async_device_update
    raise exc
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 200, in update
    map_data = self._connector.get_map(self._country, map_name, self._colors, self._drawables, self._texts,
  File "/config/custom_components/xiaomi_cloud_map_extractor/xiaomi_cloud_connector.py", line 134, in get_map
    map_data = MapDataParser.parse(unzipped, colors, drawables, texts, sizes, image_config)
  File "/config/custom_components/xiaomi_cloud_map_extractor/map_data_parser.py", line 81, in parse
    ImageHandler.draw_texts(map_data.image, texts)
  File "/config/custom_components/xiaomi_cloud_map_extractor/image_handler.py", line 193, in draw_texts
    ImageHandler.__draw_text__(image, text_config[CONF_TEXT], x, y, text_config[CONF_COLOR],
  File "/config/custom_components/xiaomi_cloud_map_extractor/image_handler.py", line 245, in __draw_text__
    ImageHandler.__draw_on_new_layer__(image, draw_func)
  File "/config/custom_components/xiaomi_cloud_map_extractor/image_handler.py", line 259, in __draw_on_new_layer__
    draw_function(draw)
  File "/config/custom_components/xiaomi_cloud_map_extractor/image_handler.py", line 236, in draw_func
    font = ImageFont.truetype(font_file, font_size)
  File "/usr/local/lib/python3.8/site-packages/PIL/ImageFont.py", line 852, in truetype
    return freetype(font)
  File "/usr/local/lib/python3.8/site-packages/PIL/ImageFont.py", line 849, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/usr/local/lib/python3.8/site-packages/PIL/ImageFont.py", line 173, in __init__
    freetype_version = parse_version(features.version_module("freetype2"))
  File "/usr/local/lib/python3.8/site-packages/packaging/version.py", line 57, in parse
    return Version(version)
  File "/usr/local/lib/python3.8/site-packages/packaging/version.py", line 296, in __init__
    match = self._regex.search(version)
`

**Comment by PiotrMachowski** [comment]
@8osman Remove `texts` section from your config, it stopped working in HA 2021.2+

**Comment by 8osman** [comment]
@PiotrMachowski great job, that's fixed it. Thank you - super speedy response

**Comment by ant0nwax** [comment]
Hi Piotr

sorry to state, but this does not work :)

HI All

I am trying to integrate my viomi.vacuum.v8
into Home Assistant running in iocage on TrueNAS (FreeBSD)

THIS IS OK
I have one integration up and running which is this one:
https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card

THIS IS NOT WORKING
I struggle with getting another integration to run because of the same issue you guys seem to have here
https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor

I get following issues:
```
ESC[31m2021-03-06 19:34:57 ERROR (SyncWorker_3) [miio.miioprotocol] Got error when receiving: timed outESC[0m
ESC[33m2021-03-06 19:35:01 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05ESC[0m
```

Debug Level Logs:
```
ESC[36m2021-03-06 19:24:54 DEBUG (SyncWorker_3) [miio.miioprotocol] Discovered 16581cc7 with ts: 2021-03-06 18:24:54, token: b'ffffffffffffffffffffffffffffffff'ESC[0m
ESC[36m2021-03-06 19:24:54 DEBUG (SyncWorker_3) [miio.miioprotocol] 192.168.1.208:54321 >>: {'id': 304, 'method': 'get_map_v1', 'params': []}ESC[0m
ESC[31m2021-03-06 19:24:59 ERROR (SyncWorker_3) [miio.miioprotocol] Got error when receiving: timed outESC[0m
ESC[33m2021-03-06 19:24:59 WARNING (SyncWorker_3) [custom_components.xiaomi_cloud_map_extractor.camera] Got exception while fetching the state: No response from the deviceESC[0m
ESC[36m2021-03-06 19:24:59 DEBUG (SyncWorker_3) [miio.miioprotocol] 192.168.1.208:54321 >>: {'id': 305, 'method': 'get_map_v1', 'params': []}ESC[0m
ESC[36m2021-03-06 19:25:04 DEBUG (SyncWorker_3) [miio.miioprotocol] Retrying with incremented id, retries left: 3ESC[0m
ESC[36m2021-03-06 19:25:04 DEBUG (SyncWorker_3) [miio.miioprotocol] Got a response: Container:
    data = Container:
        data = b'' (total 0)
        value = b'' (total 0)
        offset1 = 32
        offset2 = 32
        length = 0
    header = Container:
        data = b'!1\x00 \x00\x00\x00\x00\x16X\x1c\xc7`C\xc9\x01' (total 16)
        value = Container:
            length = 32
            unknown = 0
            device_id = b'\x16X\x1c\xc7' (total 4)
            ts = 2021-03-06 18:25:05
        offset1 = 0
        offset2 = 16
        length = 16
    checksum = b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' (total 16)ESC[0m
ESC[36m2021-03-06 19:25:04 DEBUG (SyncWorker_3) [miio.miioprotocol] Discovered 16581cc7 with ts: 2021-03-06 18:25:05, token: b'ffffffffffffffffffffffffffffffff'ESC[0m
ESC[36m2021-03-06 19:25:04 DEBUG (SyncWorker_3) [miio.miioprotocol] 192.168.1.208:54321 >>: {'id': 406, 'method': 'get_map_v1', 'params': []}ESC[0m
ESC[36m2021-03-06 19:25:09 DEBUG (SyncWorker_7) [miio.miioprotocol] 192.168.1.208:54321 >>: {'id': 3, 'method': 'get_prop', 'params': ['run_state', 'mode', 'err_state', 'battary_life', 'box_type', 'mop_type', 's_time', 's_area', 'suction_grade', 'water_grade', 'remember_map', 'has_map', 'is_mop', 'has_newmap']}ESC[0m
ESC[36m2021-03-06 19:25:09 DEBUG (SyncWorker_7) [miio.miioprotocol] 192.168.1.208:54321 (ts: 2021-03-06 18:25:09, id: 3) << {'result': [5, 0, 2105, 100, 1, 0, 1, 1.5, 3, 12, 1, 1, 0, 1], 'id': 3}ESC[0m
ESC[36m2021-03-06 19:25:09 DEBUG (SyncWorker_3) [miio.miioprotocol] Retrying with incremented id, retries left: 2ESC[0m
ESC[36m2021-03-06 19:25:10 DEBUG (SyncWorker_3) [miio.miioprotocol] Got a response: Container:
    data = Container:
        data = b'' (total 0)
        value = b'' (total 0)
        offset1 = 32
        offset2 = 32
        length = 0
    header = Container:
        data = b'!1\x00 \x00\x00\x00\x00\x16X\x1c\xc7`C\xc9\x06' (total 16)
        value = Container:
            length = 32
            unknown = 0
            device_id = b'\x16X\x1c\xc7' (total 4)
            ts = 2021-03-06 18:25:10
        offset1 = 0
        offset2 = 16
        length = 16
    checksum = b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' (total 16)ESC[0m
ESC[36m2021-03-06 19:25:10 DEBUG (SyncWorker_3) [miio.miioprotocol] Discovered 16581cc7 with ts: 2021-03-06 18:25:10, token: b'ffffffffffffffffffffffffffffffff'ESC[0m
ESC[36m2021-03-06 19:25:10 DEBUG (SyncWorker_3) [miio.miioprotocol] 192.168.1.208:54321 >>: {'id': 507, 'method': 'get_map_v1', 'params': []}ESC[0m
ESC[36m2021-03-06 19:25:15 DEBUG (SyncWorker_3) [miio.miioprotocol] Retrying with incremented id, retries left: 1ESC[0m
ESC[36m2021-03-06 19:25:15 DEBUG (SyncWorker_3) [miio.miioprotocol] Got a response: Container:
    data = Container:
        data = b'' (total 0)
        value = b'' (total 0)
        offset1 = 32
        offset2 = 32
        length = 0
    header = Container:
        data = b'!1\x00 \x00\x00\x00\x00\x16X\x1c\xc7`C\xc9\x0b' (total 16)
        value = Container:
            length = 32
            unknown = 0
            device_id = b'\x16X\x1c\xc7' (total 4)
            ts = 2021-03-06 18:25:15
        offset1 = 0
        offset2 = 16
        length = 16
    checksum = b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' (total 16)ESC[0m
ESC[36m2021-03-06 19:25:15 DEBUG (SyncWorker_3) [miio.miioprotocol] Discovered 16581cc7 with ts: 2021-03-06 18:25:15, token: b'ffffffffffffffffffffffffffffffff'ESC[0m
ESC[36m2021-03-06 19:25:15 DEBUG (SyncWorker_3) [miio.miioprotocol] 192.168.1.208:54321 >>: {'id': 608, 'method': 'get_map_v1', 'params': []}ESC[0m
ESC[31m2021-03-06 19:25:20 ERROR (SyncWorker_3) [miio.miioprotocol] Got error when receiving: timed outESC[0m
ESC[36m2021-03-06 19:25:20 DEBUG (SyncWorker_3) [miio.miioprotocol] 192.168.1.208:54321 >>: {'id': 609, 'method': 'get_map_v1', 'params': []}ESC[0m
ESC[36m2021-03-06 19:25:25 DEBUG (SyncWorker_3) [miio.miioprotocol] Retrying with incremented id, retries left: 3ESC[0m
ESC[36m2021-03-06 19:25:25 DEBUG (SyncWorker_3) [miio.miioprotocol] Got a response: Container:
```


Hope someone finds a solution one day :)

PS, i opened also this:

**Comment by andreynikolovv** [comment]
Hi @PiotrMachowski,

It is an awesome work that you have done!!!.

But I have the same issue here, the extrated map is not shown in the custom card.

Info:
HA Version:  **core-2021.3.4**
Home Assistant Supervisor: **supervisor-2021.03.6**
Host: Ubuntu: **20.04.2 LTS**
Docker Version: **20.10.5**

1. Install - lovelace-xiaomi-vacuum-map-card
-  manual as the steps in the repository
2. Install - Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor
- use HACS to install it
3.  Add the resource in the Lovelace Dashboards
- ![image](https://user-images.githubusercontent.com/14093242/111630591-31625100-87fb-11eb-9653-a75e87234267.png)

4. Configuration in configuration.yaml file
- 
![image](https://user-images.githubusercontent.com/14093242/111630825-6d95b180-87fb-11eb-88b8-e9fb6d1a855b.png)

5.  Click on the Entity with visible map
- 
![image](https://user-images.githubusercontent.com/14093242/111631165-c2d1c300-87fb-11eb-89c3-9769c6538583.png)

6.  Card configuration
- 
![image](https://user-images.githubusercontent.com/14093242/111631290-e4cb4580-87fb-11eb-896b-02ee7ebeb5f6.png)

As you can see I am not seeing the extracted map there. What I am missing?

**Comment by PiotrMachowski** [comment]
@andreynikolovv 
You don't have to install card manually and via HACS, one is enough ;)

Your problem is an incorrect value for `map_camera` in card's configuration, it should be `camera.pepeliashka`

**Comment by andreynikolovv** [comment]
> 
> 
> @andreynikolovv
> You don't have to install card manually and via HACS, one is enough ;)
> 
> Your problem is an incorrect value for `map_camera` in card's configuration, it should be `camera.pepeliashka`

lol you are awesome, thank you very much, now is visible :) :)

**Comment by PiotrMachowski** [comment]
You can check out [this issue](https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor/issues/22): Cloudflare DNS seems to block extractor

**Comment by ant0nwax** [comment]
wow thats interesting
thanks Piotr

i was using most likely 1.1.1.1 and 1.0.0.1

but why does the native MI APP work then?

at the moment my HA instance is decommissioned

Wish a good day

**Comment by PiotrMachowski** [comment]
@ant0nwax I have no idea :D

**Comment by ant0nwax** [comment]
i think I answered that before

i have some robot version 7 which was not supported by map

is it now?
its called Mi Vacuum Mop Pro
would be a reason to reevaluate HA

thank you sir

**Comment by PiotrMachowski** [comment]
No, it is still not supported :(

**Comment by ant0nwax** [comment]
okay, thank you sir, waiting patiently :)
have a good weekend

**Comment by PawelTolo** [comment]
Hi Piotr, getting errow while checking config , any advise ? 
![config](https://user-images.githubusercontent.com/106479579/171868147-43f90d81-7de6-4c3b-9cd9-21823d08a9da.JPG)
![token](https://user-images.githubusercontent.com/106479579/171868161-4243ae3e-c544-4b26-9d89-1a570c8bb048.JPG)
![failed](https://user-images.githubusercontent.com/106479579/171868337-51257a88-32c0-4de7-bcb3-749f8c31f0ae.JPG)

**Comment by PiotrMachowski** [comment]
@PawelTolo actually even two:
 - this is quite poor censorship, reading your credentials is easily doable
 - here you can check out how to handle secrets: https://www.home-assistant.io/docs/configuration/secrets/

**Comment by alejarvis** [comment]
@PiotrMachowski 

hi. i have a Xiaomi Vacuum S12. it's compatible with this model ? (xiaomi.vacuum.b106eu)

**Comment by PiotrMachowski** [comment]
@alejarvis I have no idea, I have never heard about this model. You just have to try

**Comment by alejarvis** [comment]
i have those attributes:

Model
xiaomi.vacuum.b106eu
Lan IP
192.168.1.37
MAC address
c8:5c:cc:af:b2:45
Entity class
MiotVacuumEntity
Home room
8208094218 Home
Miot type
urn:miot-spec-v2:device:vacuum:0000A006:xiaomi-b106eu:1
Vacuum.status
5
Vacuum.fault
0
Vacuum.mode
0
Vacuum.sweep type
0
Vacuum.restricted walls
[1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1]
Disturb.dnd enable
0
Disturb.dnd start hour
23
Disturb.dnd start minute
0
Disturb.dnd end hour
9
Disturb.dnd end minute
0
Disturb.multi prop dnd
[0,23,0,9,0]
Map.remember state
1
Map.cur map ID
1.692.133.107
Map.map num
1
Map.cur cleaning path
Sconosciuto
Map.build map
0
Map.has new map
0
Point zone.target point
[1100,1100]
Order.all enable count
[0,0]
Sweep.repeat state
0
Sweep.door state
3
Sweep.cloth state
1
Sweep.suction state
3
Sweep.water state
0
Sweep.mop route
0
Sweep.side brush life
88
Sweep.side brush hours
159
Sweep.main brush life
94
Sweep.main brush hours
339
Sweep.hypa life
88
Sweep.hypa hours
159
Sweep.mop life
89
Sweep.mop hours
161
Sweep.time zone
-7.200
Sweep.cur lang
it_IT
Sweep.cleaning time
2
Sweep.cleaning area
4
Sweep.dirt recognize
0
Sweep.pet recognize
0
Sweep.ai recognize
0
Sweep.carpet booster
0
Sweep.multi prop vacuum
[0,3,1,3,0,0,-7200,2,4.3,1,"it_IT","475022SD2304A09247","it_IT",6,-1,1,0,1,2,1]
Sweep.tank shake
1
Sweep.shake shift
2
Sweep.map encrypt
1
Alarm
true
Alarm.volume
2
State updater
lan
Vacuum.status desc
Sweeping
Sub entities
battery-3.battery_level-1
Miot action result
code: 0


<img width="690" alt="Screenshot 2023-08-18 at 9 13 26 PM" src="https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/assets/99549124/76cb373a-183c-4128-9f1f-780ef323150d">


cofiguration:
camera:
  - platform: xiaomi_cloud_map_extractor
    host: 192.168.1.37
    token: ###
    username: ###
    password: ###
    force_api: roidmi
    country: "de"
    scan_interval:
      seconds: 10
    auto_update: true
    store_map_raw: false
    store_map_image: true
    store_map_path: "/tmp"
    draw: ['all']
    attributes:
      - calibration_points

**Comment by PiotrMachowski** [comment]
You have to manually check different values for `force_api` and check if it works. You can also send me a raw map file.

**Comment by alejarvis** [comment]
ok i fixed: force_api: xiaomi

i have this situation atm

<img width="580" alt="Screenshot 2023-08-18 at 9 48 49 PM" src="https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/assets/99549124/e1196cbf-8450-45aa-b6af-70e629288750">

**Comment by PiotrMachowski** [comment]
Well, it doesn't seem to work. Try other values

**Comment by alejarvis** [comment]
all values tested. not work :(

**Comment by PiotrMachowski** [comment]
Create a new issue with type `Request for support of a new vacuum/platform`. Use following config to retrieve map:
```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: 192.168.1.37
    token: ###
    username: ###
    password: ###
    force_api: viomi
    country: "de"
    store_map_raw: true
    store_map_path: "/config"
    draw: ['all']
    attributes:
      - calibration_points
```

**Comment by alejarvis** [comment]
issue created. 

2023-08-19 05:08:13.598 ERROR (MainThread) [homeassistant.helpers.entity] Update for camera.xiaomi_cloud_map_extractor fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 699, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 940, in async_device_update
    await hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 278, in update
    self._handle_map_data(map_name)
  File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 335, in _handle_map_data
    map_data, map_stored = self._device.get_map(map_name, self._colors, self._drawables, self._texts,
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_cloud_map_extractor/common/vacuum.py", line 27, in get_map
    response = self.get_raw_map_data(map_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_cloud_map_extractor/common/vacuum.py", line 45, in get_raw_map_data
    map_url = self.get_map_url(map_name)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_cloud_map_extractor/common/vacuum_v2.py", line 18, in get_map_url
    if api_response is None or "result" not in api_response or "url" not in api_response["result"]:
                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable


this is my log

**Comment by tiahgo123** [comment]
@alejarvis Did you manage to solve the problem?
