### ISSUE TITLE
Info for feature Home Assistant version

### ISSUE THREAD

**Issue by Wibias** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#84]
Hey.

I am using a dev version of Home Assistant right now and I am getting this warning in my Logs:

`No 'version' key in the manifest file for custom integration 'xiaomi_cloud_map_extractor'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'xiaomi_cloud_map_extractor' `

So just a quick head up!

**Comment by PiotrMachowski** [comment]
Thanks!

**Comment by sagitt** [comment]
new version is now alvie!

**Comment by PiotrMachowski** [comment]
Working on it :)

**Comment by sagitt** [comment]
good!

**Comment by PiotrMachowski** [comment]
Fixed in v1.0.6
