### ISSUE TITLE
Problem since HA core-2021.3.0b0

### ISSUE THREAD

**Issue by bussio** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#85]
Since the new HA core-2021.3.0b0 I get the following error message:

Logger: homeassistant.components.hassio
Source: components/hassio/__init__.py:427 
Integration: Hass.io (documentation, issues) 
First occurred: 18:39:46 (1 occurrences) 
Last logged: 18:39:46

Platform error device_tracker.xiaomi_cloud_map_extractor - No module named 'custom_components.xiaomi_cloud_map_extractor.device_tracker'

Can you please take a look ....

**Comment by PiotrMachowski** [comment]
You definitely have something wrong in the config

**Comment by bussio** [comment]
You were right ... somehow the "camera:" entry has been missing.
