### ISSUE TITLE
Memory growth connected to xiaomi_cloud_map_extractor

### ISSUE THREAD

**Issue by hawaiihasse** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#86]
I have been experiencing a memory leak over the last couple of weeks that results in a crash about two times a day now. I found a way to dump my memory using the profiler integration in HA which gave me a file with 1711 rows of complete sets of data from the map_extractor. Have anyone else seen this issue before? I would expect old rows of data to be purged regularly but this seems not to be the case this time around.  Maybe I have broken something in my configuration?

Sincerely
Andreas

**Comment by PiotrMachowski** [comment]
It works perfectly fine even on my RPi3b+ with 5s update interval. What kind of data have you found?

**Comment by hawaiihasse** [comment]
I just tried restarting HA after a reinstall of the map extractor. The memory dump I get now is basically the same as what I find under current entities in the developer tools tab. Before however, the dump was so big that my browser almost crashed. Once I could past the text I found out that it contained 1711  copies on the data string that map extractor imports into HA (entity?).

I will check how the system have progressed over the night now after the reinstall and I will try to troubleshoot the issue more this weekend.

**Comment by hawaiihasse** [comment]
Hi Piotr,

I have now checked the memory dump a bit more careful and it seems my original conclusion is correct. For some reason the memory is filled with thousands of identical sets (at about 60% filled RAM I get 2927 sets of the data from the vacuum entity). By searching for text strings like " state camera.mormor=idle" or "calibration_points=[{'vacuum': {'x': 25500, 'y': 25500}" I estimate how many sets of data there is in the memory dump. However, for some reason I only get 28 hits when I search for the token string. Maybe this could be a clue to what's happening? 

To double check that this issue is isolated to the map_extractor I also tried searching for other keywords like aqura which resulted in only a handful of hits in the text file from the memory dump which would be expected (I have a couple of sensors in the system).

Do you have any suggestions for how to tackle this issue? At the moment this decreases the convenience of HA significantly as I have to reboot the system every morning and evening for it to work as expected.

**Comment by PiotrMachowski** [comment]
I will try to investigate this problem, but I am not an expert in python

**Comment by PiotrMachowski** [comment]
Can you share your config?

**Comment by hawaiihasse** [comment]
My hardware is an intel NUC on an i3 with 4 gb ram. HA is running in a container under Debian 10. 

I might need some help on how to share info regarding how I have configured HA, if that is of interest that is.

**Comment by PiotrMachowski** [comment]
Config of a camera should be enough for now

**Comment by hawaiihasse** [comment]
camera:
  - platform: xiaomi_cloud_map_extractor
    host: ---
    token: ---
    name: Mormor
    username: ---
    password: ---
    #camera_calibration: true
    country: "de"
    colors:
      color_map_inside: [0, 0, 0]
      color_map_outside: [0, 0, 0]
      color_map_wall: [255, 255, 255]
      color_map_wall_v2: [100, 100, 100]
      color_grey_wall: [93, 109, 126]
      color_path: [147, 194, 238]
      color_goto_path: [0, 255, 0]
      color_predicted_path: [255, 255, 0, 0]
      color_zones: [0xAD, 0xD8, 0xFF, 0x8F]
      color_zones_outline: [0xAD, 0xD8, 0xFF]
      color_virtual_walls: [255, 0, 0]
      color_no_go_zones: [255, 33, 55, 127]
      color_no_go_zones_outline: [255, 0, 0]
      color_no_mop_zones: [163, 130, 211, 127]
      color_no_mop_zones_outline: [163, 130, 211]
      color_charger: [0x66, 0xfe, 0xda, 0x7f]
      color_robo: [185, 0, 0]
      color_unknown: [0, 0, 0]
      color_scan: [0xDF, 0xDF, 0xDF]
    room_colors:
      1: [240, 178, 122]
      2: [15, 205, 34]#???
      3: [217, 136, 128]
      4: [52, 152, 219]
      5: [205, 97, 85]
      6: [243, 156, 18]
      7: [88, 214, 141]
      8: [245, 176, 65]
      9: [252, 212, 81]#hallentoa
      10: [72, 201, 176]
      11: [84, 153, 199]
      12: [133, 193, 233]
      13: [245, 176, 65]
      14: [82, 190, 128]
      15: [72, 201, 176]#benjamins
      16: [165, 105, 18]#vardagsrummet
    draw:
      - charger
      - path
      - goto_path
      - predicted_path
      - no_go_zones
      - no_mopping_zones
      - vacuum_position
      - virtual_walls
      - zones
    texts:
      - text: "Benjamins"
        x: 25
        y: 20
        color: [125, 20, 213]
      - text: "Vardagsrummet"
        x: 40
        y: 60
        color: [20, 20, 215]
      - text: "Hallen"
        x: 50
        y: 32
        color: [32, 19, 215]
      - text: "Toan"
        x: 64
        y: 22
        color: [32, 19, 215]
        #font: "FreeSans.ttf"
        font_size: 42
    map_transformation:
      scale: 2
      rotate: 0
      trim:
        top: 20
        bottom: 10
        left: 25
        right: 10
    sizes:
      charger_radius: 4
      vacuum_radius: 6.5
    attributes:
      - calibration_points
      - charger
      - goto
      - goto_path
      - goto_predicted_path
      - image
      - is_empty
      - map_name
      - no_go_areas
      - no_mopping_areas
      - obstacles
      - path
      - room_numbers
      - rooms
      - vacuum_position
      - vacuum_room
      - walls
      - zones
    scan_interval:
      seconds: 10
    auto_update: true

**Comment by PiotrMachowski** [comment]
You probably can remove all values from `attributes` section (except `calibration_points` of you use the map card), it should reduce memory and DB usage

**Comment by hawaiihasse** [comment]
I will try that! Hopefully the issue will disappear but probably I'll just won't have to restart as often.

**Comment by hawaiihasse** [comment]
So far so good, thank you for the assistance! 

![Screenshot_20210227-212158](https://user-images.githubusercontent.com/55664313/109399231-ea8ee300-7941-11eb-87c1-f0bd5438f975.jpg)

**Comment by hfcheng66** [comment]
Could you explain more how those attributes could be used?
Currently I only have "calibration_points" there, is this required for the interactive map to use this map as "map_camera"?

**Comment by PiotrMachowski** [comment]
@hfcheng66 they were added for the future version of map card. Some of them can also be used in different ways: you can track which room is being cleaned at this moment, get a list of rooms' numbers...

**Comment by GegoSK** [comment]
I am not sure, but I think I have very similiar problem. Therefore I don't want to start a new topic. If I should do it, just tell me. 

During months the memory usage was 70-90%. Around November 19th (Core 2021.11.1), it started to increase and then HA freeze, few minutes after restart again another freeze. Check this:
![image](https://user-images.githubusercontent.com/65870850/148395176-764da3e1-dbfb-441b-9ca1-772c2f2c31c7.png)
Next days, it took few hours to crash. Third day, everything ok. I did not know what was the problem. Since this situation, I'm monitoring Memory usage, CPU load and temperature. 

On December 31st, map disappeared, because some change on xiaomi servers. Mermory usage dropped down to 60%.
![image](https://user-images.githubusercontent.com/65870850/148396069-d5259284-b267-4111-8043-d65045d0f0b4.png)
 
Xiaomi map extractor was updated and restarted on January 3rd. Since then again, one freeze after another.
![image](https://user-images.githubusercontent.com/65870850/148396543-53d308f1-b257-48e7-96d8-cb2097c6adf6.png)

After turning on and off many addons, I found out it was Xiaomi map extractor. I read this discussion and remove all attributes (some of them was even useless for me) except calibration_points, vacuum_position and vacuum_room. Turn off autoupdate and map_store. Camera is in HA recorder's exclude list. I made an automation, which reload camera every 5s or 10s only during vacuuming. After 15 minutes had to stop. Memory is high ever hour after vacuuming. This is result: 
![image](https://user-images.githubusercontent.com/65870850/148398300-2f43d3ff-3b8f-4ca8-8cb0-01f61efb98f9.png)

Rp3b, 1gb RAM, 32gb sd card, core-2021.12.7. Vacuum Roborock S5. 

I do not know if this is problem related to addon or to my hardware.

**Comment by PiotrMachowski** [comment]
@GegoSK can you show your config?

**Comment by GegoSK** [comment]
@PiotrMachowski thank you for quick anwer. This is my last config from today's testing (last graph). 

camera:
  - platform: xiaomi_cloud_map_extractor
    host: 192.168.0.87
    token: xxx
    username: xxx
    password: xxx
    country: "de"
    name: "Vysávač"
    colors:
      color_map_inside: [0, 0, 0] 
      color_map_outside: [0, 0, 0] 
      color_map_wall_v2: [255, 255, 255] 
      color_path: [147, 194, 238]
      color_goto_path: [0, 255, 0]
      color_zones: [0xAD, 0xD8, 0xFF, 0x8F]
      color_zones_outline: [0xAD, 0xD8, 0xFF]
      color_virtual_walls: [255, 0, 0]
      color_no_go_zones: [255, 33, 55, 127]
      color_no_go_zones_outline: [255, 0, 0]
      color_charger: [0x66, 0xfe, 0xda, 0x7f]
      color_robo: [75, 235, 149]
      color_unknown: [0, 0, 0]
      color_scan: [0xDF, 0xDF, 0xDF]
    room_colors: 
      16: [50, 50, 50] 
      17: [50, 50, 50] 
      19: [50, 50, 50] 
      20: [50, 50, 50] 
      21: [50, 50, 50] 
      22: [50, 50, 50] 
      23: [50, 50, 50] 
      24: [50, 50, 50] 
      18: [0, 0, 0] 
    draw: 
      - charger
      - path
      - goto_path
      - no_go_zones
      - vacuum_position
      - virtual_walls
      - zones
    map_transformation:
      scale: 3 
      rotate: 0
      trim:
        top: 29
        bottom: 32
        left: 23.7
        right: 24.7
    sizes:
      charger_radius: 5
      vacuum_radius: 7.5
    attributes:
      - calibration_points
      - vacuum_position
      - vacuum_room
    scan_interval:
      seconds: 10
    auto_update: false
    store_map_raw: false
    store_map_image: false
    # store_map_path: "/tmp"
    # force_api: xiaomi

**Comment by PiotrMachowski** [comment]
Hmmm, can you reduce scale as well?

**Comment by GegoSK** [comment]
@PiotrMachowski I tried **scale: 2** and **scale: 1**. After vacuuming a small area, looks much better. In both cases, memory use increase from 65% to 75% and stay there for some time. I will let you know after more tests. Picture is a little uglier, but scale:2 is acceptable. Thank you very much!

**Comment by PiotrMachowski** [comment]
By the way, scale doesn't have to be an integer, you can use e.g. `2.1`

**Comment by PiotrMachowski** [comment]
v2.2.0 should improve memory usage
