### ISSUE TITLE
No 'version' key in the manifest file

### ISSUE THREAD

**Issue by bjakobs** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#87]
Logger: homeassistant.loader
Source: loader.py:802
First occurred: 11:53:06 AM (1 occurrences)
Last logged: 11:53:06 AM

No 'version' key in the manifest file for custom integration 'xiaomi_cloud_map_extractor'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'xiaomi_cloud_map_extractor'

**Comment by PiotrMachowski** [comment]
Duplicate #84, already fixed
