### ISSUE TITLE
Wont show the camera map

### ISSUE THREAD

**Issue by LasseTheDude** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#88]
Hi

I have tried several different configuration.yaml codings now, but I dont get the map to show.

Can you please help me?

**Comment by PiotrMachowski** [comment]
Try [this one](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#recommended). You can check credentials and token using [this tool](https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor)
