### ISSUE TITLE
Map Rotation

### ISSUE THREAD

**Issue by tbkon3** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#89]
in my hassio config i've 2 camera for 2 different view.
First camera is with Zero degree rotation, and it's ok, zone are good.

In my second camera i configure map_transformation: >> rotate: 270
The image of camera it's ok, but all zone are not rotated.
I try also with "camera_calibration: true" but i think that XY coord must be changed (270° ?) and i don't know how.

Image of both cards here: https://i.ibb.co/cDWSf0n/rotation.png

Here below my camera config, card config and camera entity detail for both cams/viwes (0° Ok and 270° don't work)
https://pastebin.com/6WP5a2be

Let me know if you need other details, thank you.

**Comment by tbkon3** [comment]
Hi PiotrMachowski, do you find a solution about this issue?

**Comment by jerometerrier** [comment]
Hello,
Same issue for me.
I'm trying to read and understand the code to purpose a pull request.
@PiotrMachowski : do you have some recommandation for the pull request ?
Thanks

**Comment by eratnik** [comment]
Hi! I have a similar problem - almost every time when cleaning, the map is rotated (90 or 180 degrees) and all zones are rotated and / or displaced. Vacuum cleaner - mi vacuum cleaner 1st generation. Can I fix this somehow? Maybe a custom firmware?
The configuration is standard. [https://ibb.co/q9QchD4](url)
PS I apologize for my English - I am using a translator.

**Comment by PiotrMachowski** [comment]
@jerometerrier it would be great if you could send me your map file (using `store_map: true`) at `piotr.machowski [at] gmail [dot] com`

@eratnik this is a different issue and I'm afraid that it can't be solved

**Comment by tbkon3** [comment]
Hi @PiotrMachowski  where can i add store_map: true to send you map file?

**Comment by PiotrMachowski** [comment]
Hi @tbkon3, it is at the bottom of [full configuration](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#full), but with `false`. Map file will be saved in `/tmp/map_data.gz`

**Comment by danielntamasi** [comment]
same issue here

**Comment by PiotrMachowski** [comment]
It would really help if someone could send me map data

**Comment by danielntamasi** [comment]
I can do that later this week. 

Quick background for you: I had the same issue when I rooted my vacuum cleaner last year and connected to HA that way. 
As storing maps / rooms are not natively supported by the 1st gen Xiaomi vacuum cleaner, maps tend to rotate when you start a new cleanup. 

It seems haphazard which direction it rotates (it's always by 90 degree increments).

So, I don't think this is a bug with your solution, but if you have a way to reverse engineer it - e.g.: setting the map transformation dynamically so it always fits the randomness of the Xiaomi map - that would be helpful.

But as I said before, I'll send you the maps later this week.

**Comment by PiotrMachowski** [comment]
@danielntamasi oh, ok, I thought that you have a problem with my solution (the original topic of this issue). Solving your problem is a tricky stuff to do, maaaaaaybe I will be able to find a workaround for it

**Comment by jerometerrier** [comment]
Sorry for the delay, i just change the configuration to generate the map, but still nothing in the tmp folder.
Maybe i have to start the vacuum to generate it. 
I will try tomorrow, not possible for me to start the vacuum right now (children are sleeping :) )

And i think my issue is exactly the same than the @danielntamasi 's one. 
In my mind, i imagine the possibility to change a value in the GUI to rotate zones easily...(and why not the same with the rotate parameter about the map... ?)

**Comment by PiotrMachowski** [comment]
@jerometerrier you don't have to start vacuuming, it should be generated right away. It should be inside homeassistant container (if you use HA supervised), not in the OS.

**Comment by danielntamasi** [comment]
@PiotrMachowski, I'm also struggling finding the /tmp folder. 

Could you please elaborate how to navigate to it?

Thank you for your answer in advance.

**Comment by PiotrMachowski** [comment]
- In [SSH & Terminal add-on](https://github.com/hassio-addons/addon-ssh) enable protected access
- Open terminal and connect to HA container using command: `docker exec -it homeassistant bash`
- Map file should be in`/tmp` directory, you can copy it to `/config` and retrieve it in any way you like
(Sorry for any mistakes, I write this from the memory)

**Comment by danielntamasi** [comment]
@PiotrMachowski I'm still having trouble locating the map file.

Below is my HA config for your solution and my terminal output for tmp folder(s).

**This is my terminal output through different containers (I have HA installed on Raspberry PI OS + Supervised HA):**
```
pi@raspberrypi:~ $ docker ps
CONTAINER ID   IMAGE                                               COMMAND                  CREATED        STATUS        PORTS                                   NAMES
a30cfe95c524   ghcr.io/hassio-addons/node-red/armv7:9.1.1          "/init"                  14 hours ago   Up 14 hours                                           addon_a0d7b954_nodered
d2cb687466af   homeassistant/armv7-addon-configurator:5.3.0        "/init"                  14 hours ago   Up 14 hours                                           addon_core_configurator
d4f60ac007fb   homeassistant/armv7-addon-ssh:9.1.3                 "/init"                  14 hours ago   Up 14 hours                                           addon_core_ssh
233cbedc65c5   homeassistant/armv7-addon-duckdns:1.12.5            "/init /run.sh"          14 hours ago   Up 14 hours                                           addon_core_duckdns
631496f3d31f   homeassistant/armv7-hassio-multicast:2021.04.0      "/init"                  14 hours ago   Up 14 hours                                           hassio_multicast
23c81b32558c   homeassistant/armv7-hassio-cli:2021.05.1            "/init /bin/bash -c …"   14 hours ago   Up 14 hours                                           hassio_cli
7ef19b9e2496   homeassistant/armv7-hassio-audio:2021.04.0          "/init"                  14 hours ago   Up 14 hours                                           hassio_audio
48348342ccb   homeassistant/armv7-hassio-dns:2021.04.0            "/init"                  14 hours ago   Up 14 hours                                           hassio_dns
6796c03e9594   homeassistant/raspberrypi4-homeassistant:2021.5.5   "/init"                  10 days ago    Up 14 hours                                           homeassistant
fd693e18399e   homeassistant/armv7-hassio-supervisor               "/init"                  2 weeks ago    Up 14 hours                                           hassio_supervisor
04c3163e8ab5   homeassistant/armv7-hassio-observer:2020.10.1       "/init"                  2 weeks ago    Up 14 hours   0.0.0.0:4357->80/tcp, :::4357->80/tcp   hassio_observer
pi@raspberrypi:~ $ docker exec -it homeassistant bash
bash-5.0# ls
automations.yaml          groups.yaml               image                     themes
blueprints                home-assistant.log        node-red                  tts
configuration.yaml        home-assistant_v2.db      scenes.yaml               www
custom_components         home-assistant_v2.db-shm  scripts.yaml
deps                      home-assistant_v2.db-wal  secrets.yaml
bash-5.0# cd tmp
bash: cd: tmp: No such file or directory
bash-5.0# exit
exit
pi@raspberrypi:~ $ docker exec -it hassio_supervisor bash
bash-5.1# ls
bin      dev      home     lib      media    opt      root     sbin     sys      usr
data     etc      init     libexec  mnt      proc     run      srv      tmp      var
bash-5.1# cd tmp
bash-5.1# ls
tmph8sgle7w
bash-5.1# exit
exit
pi@raspberrypi:~ $ docker exec -it addon_core_configurator bash
bash-5.0# ls
backup   config   dev      home     lib      media    opt      root     sbin     srv      sys      usr
bin      data     etc      init     libexec  mnt      proc     run      share    ssl      tmp      var
bash-5.0# cd tmp
bash-5.0# ls
bash-5.0# exit
exit
pi@raspberrypi:~ $ docker exec -it hassio_cli bash
bash-5.1# ls
bin      etc      init     libexec  mnt      proc     run      srv      tmp      var
dev      home     lib      media    opt      root     sbin     sys      usr
bash-5.1# cd tmp
bash-5.1# ls
bash-5.1# exit
exit
pi@raspberrypi:~ $ docker exec -it hassio_cli bash
bash-5.1# ls
bin      etc      init     libexec  mnt      proc     run      srv      tmp      var
dev      home     lib      media    opt      root     sbin     sys      usr
bash-5.1# cd tmp
bash-5.1# ls

```

**HA Config**
```
camera:
  - platform: xiaomi_cloud_map_extractor
    host: 192.168.0.114
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    colors:
      color_map_inside: [198, 232, 197]
      color_map_outside: [247, 247, 246]
      color_map_wall: [0, 170, 0]
      color_path: [2, 143, 167]
      color_zones: [244, 150, 110]
      color_zones_outline: [247, 91, 24]
      color_goto_path: [247, 206, 24]
      color_predicted_path: [239, 226, 167]
      color_charger: [250, 231, 2]
      color_robo: [132, 132, 132]
    draw: ["all"]
    store_map: true
    scan_interval: 2
    map_transformation:
      scale: 2
      trim:
        top: 24
        bottom: 12
        left: 5
        right: 19
    attributes:
      - calibration_points
```

**Comment by PiotrMachowski** [comment]
```
pi@raspberrypi:~ $ docker exec -it homeassistant bash
bash-5.0# ls
automations.yaml          groups.yaml               image                     themes
blueprints                home-assistant.log        node-red                  tts
configuration.yaml        home-assistant_v2.db      scenes.yaml               www
custom_components         home-assistant_v2.db-shm  scripts.yaml
deps                      home-assistant_v2.db-wal  secrets.yaml
bash-5.0# cd tmp
bash: cd: tmp: No such file or directory
```

Can you check following commands:
```
docker exec -it homeassistant bash
cd /
ls
cd tmp
```

**Comment by jerometerrier** [comment]
Hello
@danielntamasi 

an easier way : 
```
docker exec -it homeassistant cp /tmp/map_data.gz /config/tmp
```

After this command, you will find the file in your tmp folder of the config folder

@PiotrMachowski  : file send by mail, thanks for your help :)

**Comment by PiotrMachowski** [comment]
@jerometerrier daaaaamn, I have made mistake in email address... Here you have the correct one: `piotr.machowski.dev [at] gmail [dot] com`

**Comment by jerometerrier** [comment]
I just send it again. 😊

**Comment by danielntamasi** [comment]
@PiotrMachowski just sent it to you. Thank you, Piotr and @jerometerrier for the guidance finding the map_data file.

**Comment by PiotrMachowski** [comment]
@tbkon3 can you check if the problem has been solved in v2.x.x?

**Comment by jerometerrier** [comment]
@PiotrMachowski , first try seems to be ok for me.
Now, be able to do something like that in the configuration should be the best :)

```
    map_transformation:
      rotate: !input xiaomi_vacuum_map_rotation
```

(because i use the first version and sometimes, the map rotate by itself.

Anyway, thank you for the amazing job... 👏

**Comment by PiotrMachowski** [comment]
@jerometerrier this will not help - zones will still be misplaced in map-card

**Comment by jerometerrier** [comment]
@PiotrMachowski  : ok, i will have a look, seems than it works for now.
Anyway thank you

**Comment by danielntamasi** [comment]
The map still rotates for me. I'm on 2.0.2.

**Comment by PiotrMachowski** [comment]
@danielntamasi and as you use gen 1, it always will. There needs to be a dedicated code that will detect that vacuum decided to rotate the map and then fix it.

**Comment by rbalaev** [comment]
> @danielntamasi and as you use gen 1, it always will. There needs to be a dedicated code that will detect that vacuum decided to rotate the map and then fix it.

what's the code to fix rotation?

**Comment by PiotrMachowski** [comment]
@rbalaev currently there is no code that solves this issue
