### ISSUE TITLE
token not accepted 

### ISSUE THREAD

**Issue by m7mdmuneer** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#90]
hello,
am trying to add the vacuum to home assistant 
but am getting this error, which is wrong because the only error that is codes accept latter and my token only numbers

Invalid config for [camera.xiaomi_cloud_map_extractor]: expected str for dictionary value @ data['token']. Got 7147765**********************5543794347. (See ?, line ?).

token is 100% correct when i removed one number and add latter am getting valid config

**Comment by PiotrMachowski** [comment]
You just have to wrap it around in single or double quotes:
```
token: "123456"
```

**Comment by m7mdmuneer** [comment]
thanks.
it's worked
