### ISSUE TITLE
Way to extract coordinates from extractor

### ISSUE THREAD

**Issue by Jese44** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#98]
Could it be possible to get coordinates/parameters of zones from map extractor, so i could use nodered to do clean automations.
Here's the nodered-vacuum guide i'm referring to:
https://aarongodfrey.dev/home%20automation/integrating_the_roborock_s4_in_home_assistant/

**Comment by PiotrMachowski** [comment]
You can do it in [my Lovelace map card](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card) with `debug: true`

**Comment by PiotrMachowski** [comment]
You can also try to use `rooms` and `room_numbers` attributes for map extractor: [documentation](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#attributes-configuration)

**Comment by Jese44** [comment]
Ok, cool! I'll try these. Thanks for help :)
