### ISSUE TITLE
Support for ViomiSE vacuum cleaner

### ISSUE THREAD

**Issue by Chriserus** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#99]
Hi!
Is there any possibility of Viomi SE vacuum cleaner support? Or it differs from other vacuums (Xiaomi, Roborock) in a way, that map extraction is really hard? Would love to see support for this model :)
Best regards,
Krzysztof

**Comment by PiotrMachowski** [comment]
Unfortunately as far as I know all Viomi models have a different (not fully known) maps API.
See #23
